import type { MetadataRoute } from "next";

import { siteConfig } from "@/lib/site";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: `${siteConfig.url}/traning/viktvast`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/hopprep`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/luftrenare`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/tangle-teezer`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/silkesorngott`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/gua-sha`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/laneige-lappmask`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/cicaplast-b5`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/cerave-rengoring`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/vitamin-c-serum`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: siteConfig.url,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 1,
    },
    {
      url: `${siteConfig.url}/om-oss`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${siteConfig.url}/kontakt`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${siteConfig.url}/samarbeta`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${siteConfig.url}/integritetspolicy`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.3,
    },
    {
      url: `${siteConfig.url}/cookies`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.3,
    },
    {
      url: `${siteConfig.url}/kategorier`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.55,
    },
    {
      url: `${siteConfig.url}/elins-val`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.65,
    },
    {
      url: `${siteConfig.url}/jamforelser`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.72,
    },
    {
      url: `${siteConfig.url}/guider`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${siteConfig.url}/guider/snail-mucin-vart-hypen`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/tyst-flakt-sovrum`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.78,
    },
    {
      url: `${siteConfig.url}/guider/flakt-dyr-vs-billig`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.78,
    },
    {
      url: `${siteConfig.url}/guider/dyson-airwrap-eller-varmluftsborste`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.78,
    },
    {
      url: `${siteConfig.url}/guider/moroccanoil-vart-priset`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/dyr-plattang-eller-budget`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/torrschampo-dyrt-vs-billigt`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/harinpackning-salongsmarke-vart-det`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/hyaluronsyra-dyrt-vs-budget`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/niacinamide-10-vs-20`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/brun-utan-sol-vart-det`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/after-sun-eller-fuktkram`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/jojobaolja-multitalang`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/kettlebell-mjuk-vs-gjutjarn`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/dyr-massagepistol-vs-budget`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/premium-yogamatta-vs-budget`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/traningsband-dyrt-vs-billigt`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/foam-roller-dyr-vs-billig`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/sommar`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.78,
    },
    {
      url: `${siteConfig.url}/elins-poang`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.45,
    },
    {
      url: `${siteConfig.url}/traning`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${siteConfig.url}/traning/traningsband-naturlatex`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/traning/traningsband`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/traning/traningsband/loopband-jakkofoxx`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/kettlebell`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/traning/kettlebell-eller-hantlar`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/traning/kettlebell/amazon-basics`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/kettlebell/proiron-mjuk`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/hantlar`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/traning/hantlar/proiron-neopren`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/hantlar/songmics-set`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/yogamatta`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/traning/yogamatta/prosourcefit-13mm`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/yogamatta/yogati-tpe`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/foam-roller`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/traning/foam-roller-eller-massagepistol`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/traning/foam-roller/bodymate-care`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/foam-roller/elvire-deep-tissue`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${siteConfig.url}/halsa/kobo-clara-bw`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/aromdiffuser`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/solnedgangslampa`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/mini-projektor`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/stjarnprojektor`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/massagepistol`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/halsa/flakt`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/halsa/mini-projektor-eller-stjarnprojektor`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/halsa/massagepistol/beurer-mg-99`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/massagepistol/kraftfull`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/flakt/dreo-cruiser-pro`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/flakt/honeywell-turboforce`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/flakt/midea-fz10`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${siteConfig.url}/skonhet/platta-eller-locka`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/varmluftsborste-eller-fon`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/sommarglow-utan-sol`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/harolja-eller-varmeskydd`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/varmluftsborste-eller-plattang`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/aftersun-eller-aloe-vera`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/harinpackning-eller-harolja`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/brun-utan-sol`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/bronzing-drops`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/aftersun`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/aloe-vera-gel`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/hyaluronsyra-serum`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/snail-mucin-essence`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/jojobaolja`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/niacinamide-serum`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/harolja`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/harinpackning`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/torrschampo`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/elektrisk-fotfil`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/varmeskydd`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/plattang`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/plattang/remington-s8540`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/plattang/remington-mini-s2880`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/epilator`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/epilator/panasonic-es-ey30`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/epilator/braun-silk-epil-9`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/hartork`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/hartork/remington-proluxe-ac9140`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/hartork/beurer-hc-25`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/locktang`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/locktang/babyliss-c325e`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/locktang/tymo-curlpro`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/varmluftsborste`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/varmluftsborste/babyliss-as126e`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/varmluftsborste/remington-as7100`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
  ];
}
