import type { MetadataRoute } from "next";

import { siteConfig } from "@/lib/site";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: `${siteConfig.url}/halsa/hygrometer`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/motiverande-vattenflaska`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/termos`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/eltandborste`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/robotdammsugare`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/led-list`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/laslampa`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/bluetooth-hogtalare`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/oronproppar`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/sovmask`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/wake-up-light`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/white-noise`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/personvag`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/spikmatta`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/varmedyna`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/fotmassage`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/massagekudde`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/luftkylare`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/bordsflakt`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/handflakt`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/tyngdtacke`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/luftfuktare`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/luftavfuktare`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/lifting-straps`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/vattenflaska`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/loparvast`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/knaskydd`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/agility-stege`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/studsmatta`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/core-slider`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/stepbrada`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/pilatesring`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/yogabalte`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/yogablock`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/lyftarbalte`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/handledslindor`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/traningshandskar`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/miniband`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/gymnastikringar`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/push-up-handtag`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/pull-up-bar`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/maghjul`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/balansplatta`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/gymboll`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/justerbara-hantlar`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/sminksvamp`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/sminkborstar`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/press-on-naglar`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/nagelvard-set`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/halkram`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/foot-peel-mask`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/ansiktstrimmer`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/ipl-harborttagning`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/rakapparat-dam`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/kroppsskrubb`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/sjalvbrun-vante`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/tanning-drops`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/brun-utan-sol-mousse`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/frisorsax`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/texturspray`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/harspray`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/harmousse`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/volympuder`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/denman-borste`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/wet-brush`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/claw-clips`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/heatless-curls`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/satinmossa`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/microfiberhandduk`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/varmeskyddsspray`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/curl-cream`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/leave-in-conditioner`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/scalp-scrub`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/rosmarinolja`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/olaplex-no3`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/olaplex-balsam`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/olaplex-schampo`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/handkram`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/kroppslotion`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/nattkram`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/lip-oil`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/pimple-patches`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/ansiktsolja`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/ansiktsmist`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/peptidserum`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/azelainsyra-serum`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/propolis-serum`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/centella-serum`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/sheet-mask`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/lermask`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/ogonserum`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/fuktkram`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/exfolierande-toner`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/micellart-vatten`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/rengoringsolja`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/cetaphil-rengoring`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/bha-exfoliant`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/ansiktspeeling`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/bakuchiol-serum`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/viktvast`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/hopprep`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/luftrenare`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/tangle-teezer`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/silkesorngott`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/gua-sha`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/laneige-lappmask`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/cicaplast-b5`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/cerave-rengoring`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/vitamin-c-serum`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: siteConfig.url,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 1,
    },
    {
      url: `${siteConfig.url}/om-oss`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${siteConfig.url}/kontakt`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${siteConfig.url}/samarbeta`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${siteConfig.url}/integritetspolicy`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.3,
    },
    {
      url: `${siteConfig.url}/cookies`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.3,
    },
    {
      url: `${siteConfig.url}/kategorier`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.55,
    },
    {
      url: `${siteConfig.url}/elins-val`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.65,
    },
    {
      url: `${siteConfig.url}/jamforelser`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.72,
    },
    {
      url: `${siteConfig.url}/guider`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${siteConfig.url}/guider/snail-mucin-vart-hypen`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/tyst-flakt-sovrum`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.78,
    },
    {
      url: `${siteConfig.url}/guider/flakt-dyr-vs-billig`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.78,
    },
    {
      url: `${siteConfig.url}/guider/dyson-airwrap-eller-varmluftsborste`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.78,
    },
    {
      url: `${siteConfig.url}/guider/moroccanoil-vart-priset`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/dyr-plattang-eller-budget`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/torrschampo-dyrt-vs-billigt`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/harinpackning-salongsmarke-vart-det`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/hyaluronsyra-dyrt-vs-budget`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/niacinamide-10-vs-20`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/brun-utan-sol-vart-det`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/after-sun-eller-fuktkram`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/jojobaolja-multitalang`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/kettlebell-mjuk-vs-gjutjarn`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/dyr-massagepistol-vs-budget`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/premium-yogamatta-vs-budget`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/traningsband-dyrt-vs-billigt`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/guider/foam-roller-dyr-vs-billig`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.74,
    },
    {
      url: `${siteConfig.url}/sommar`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.78,
    },
    {
      url: `${siteConfig.url}/elins-poang`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.45,
    },
    {
      url: `${siteConfig.url}/traning`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${siteConfig.url}/traning/traningsband-naturlatex`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/traning/traningsband`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/traning/traningsband/loopband-jakkofoxx`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/kettlebell`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/traning/kettlebell-eller-hantlar`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/traning/kettlebell/amazon-basics`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/kettlebell/proiron-mjuk`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/hantlar`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/traning/hantlar/proiron-neopren`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/hantlar/songmics-set`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/yogamatta`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/traning/yogamatta/prosourcefit-13mm`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/yogamatta/yogati-tpe`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/foam-roller`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/traning/foam-roller-eller-massagepistol`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/traning/foam-roller/bodymate-care`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/traning/foam-roller/elvire-deep-tissue`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${siteConfig.url}/halsa/kobo-clara-bw`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/aromdiffuser`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/solnedgangslampa`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/mini-projektor`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/stjarnprojektor`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/massagepistol`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/halsa/flakt`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/halsa/mini-projektor-eller-stjarnprojektor`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/halsa/massagepistol/beurer-mg-99`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/massagepistol/kraftfull`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/flakt/dreo-cruiser-pro`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/flakt/honeywell-turboforce`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/halsa/flakt/midea-fz10`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${siteConfig.url}/skonhet/platta-eller-locka`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/varmluftsborste-eller-fon`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/sommarglow-utan-sol`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/harolja-eller-varmeskydd`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/varmluftsborste-eller-plattang`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/aftersun-eller-aloe-vera`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/harinpackning-eller-harolja`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/brun-utan-sol`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/bronzing-drops`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/aftersun`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/aloe-vera-gel`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/hyaluronsyra-serum`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/snail-mucin-essence`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/jojobaolja`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/niacinamide-serum`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/harolja`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/harinpackning`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/torrschampo`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/elektrisk-fotfil`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/varmeskydd`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/plattang`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/plattang/remington-s8540`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/plattang/remington-mini-s2880`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/epilator`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/epilator/panasonic-es-ey30`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/epilator/braun-silk-epil-9`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/hartork`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/hartork/remington-proluxe-ac9140`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/hartork/beurer-hc-25`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/locktang`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/locktang/babyliss-c325e`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/locktang/tymo-curlpro`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/varmluftsborste`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${siteConfig.url}/skonhet/varmluftsborste/babyliss-as126e`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
    {
      url: `${siteConfig.url}/skonhet/varmluftsborste/remington-as7100`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.82,
    },
  ];
}
