import type { DecisionRecord } from "@/lib/decision-record";

export const bedroomFanPaths = ["/halsa/flakt/dreo-cruiser-pro", "/halsa/flakt/midea-fz10", "/halsa/flakt/midea-golvflakt", "/halsa/bordsflakt", "/halsa/flakt/honeywell-turboforce"] as const;
export const bedroomFanDecision: DecisionRecord = {
  reviewedAt: "2026-09-08",
  options: [
    { productSlug: "dreo-cruiser-pro-tornflakt", model: "Dreo Cruiser Pro T1", variant: "Katalogens T1 och ASIN B08PDDSDHY är inte matchade mot en läst manual. Dreos aktuella TF518-sida bevisar inte att den svenska listningen gäller samma version.", chooseIf: "du vill undersöka en tornfläkt och först kan få exakt modell, reglage och displayfunktion bekräftade. Underlaget räcker ännu inte för att rekommendera just T1 för sömn.", avoidIf: "ditt köp beror på att den ska vara tystast eller ha nio hastigheter och helt släckt display. Vi har inte verifierat de uppgifterna för denna listning.", sourceIds: ["F3", "F4"], merchantVariantVerified: false },
    { productSlug: "midea-fz10-tornflakt", model: "Midea FZ10-17JR", variant: "Tysk tillverkarsida: FZ10-17JR, EAN 4048164103201, höjd 918 mm. Svensk leveransvariant är inte matchad.", chooseIf: "du söker en tornfläkt med tre hastigheter, timer och fjärrkontroll. Kontrollera att ljudet vid användbar hastighet passar dig innan du väljer den för sovrummet.", avoidIf: "du behöver bevisad tyst drift vid sängen eller en display som säkert slocknar helt. Tillverkarens lästa sida styrker inte detta.", sourceIds: ["F1"], merchantVariantVerified: false },
    { productSlug: "midea-golvflakt", model: "Midea MFS400", variant: "Namnet kommer från vår katalog. ASIN B0CPSPXN9W kunde inte läsas; exakt modellbeteckning och utförande är inte styrkta.", chooseIf: "du undersöker en golvfläkt och kan invänta verifiering av modellen. Vi saknar tillräckligt underlag för ett konkret köpråd om MFS400.", avoidIf: "du förlitar dig på uppgifterna om DC-motor, åttatimmarstimer eller särskilt tyst drift. Dessa är ännu inte verifierade för rätt variant.", sourceIds: ["F5"], merchantVariantVerified: false },
    { productSlug: "xiaomi-bordsflakt", model: "Mi Smart Standing Fan 2 Lite", variant: "Xiaomis Singapore-specifikation gäller JLLDS01XY med AC-motor och Wi-Fi 2,4 GHz. Inte automatiskt samma produkt som Smart Standing Fan 2 utan Lite.", chooseIf: "du överväger den specificerade modellen och har kontrollerat appregion, nätverk och den version som butiken levererar. Uppkoppling är ett val av bekvämlighet, inte ett bevis på bättre sömn.", avoidIf: "du behöver styrkt låg ljudnivå vid en bestämd hastighet eller svensk app- och leveranskompatibilitet utan ytterligare kontroll. Specifikationen ensam besvarar inte det.", sourceIds: ["F2"], merchantVariantVerified: false },
    { productSlug: "honeywell-turboforce-ht900e", model: "Honeywell TurboForce HT900E", variant: "Katalogens HT900E, ASIN B003KHJO6G. Butikssidan kunde inte läsas och någon manual för exakt E-version är inte verifierad här.", chooseIf: "du vill undersöka denna modell och kan kontrollera dess mått, placering och reglage före köp. Vi har inte tillräckligt underlag för att rekommendera eller avråda från den som sovrumsfläkt.", avoidIf: "du behöver ett styrkt besked om nattljud. Ett enskilt kundomdöme eller uppgifter om HT900 utan E fastställer inte ljudet från denna variant.", sourceIds: ["F6"], merchantVariantVerified: false },
  ],
  payMoreWhen: "Du får en verifierad funktion som löser ett konkret problem: exempelvis reglage du når från sängen, en display som kan släckas eller fler användbara hastigheter. Kontrollera funktionen i manualen för exakt modell. Vi har inte jämförbara aktuella priser eller ett gemensamt ljudtest som motiverar ett dyrare val.",
  noPurchaseWhen: "Fläkten du redan har ger ett luftflöde och ljud du trivs med på en säker plats enligt dess manual. Prova befintliga hastigheter och placering innan du köper en till. App, nattläge och högre pris är inte egna skäl att byta.",
  swedishContext: "Mideas tyska sida anger 220–240 V, 50 Hz. Xiaomis Singapore-sida anger 220–230 V, 50/60 Hz. Uppgifterna styrker inte svensk stickkontakt, appregion, leverans eller villkor för den aktuella butiksvaran. Kontrollera detta för den variant du beställer.",
  testing: "Vi har inte provat dessa fläktar eller mätt ljud, luftflöde, displayljus eller sömnkomfort. Två specifikationer och en Dreo-sida har lästs. Tre kataloglistningar kunde inte läsas. Ordningen är inte en rangordning.",
  limitations: "Ingen vinnare i tystnad utses. Mideas 62 dB(A) anges som ljudeffektnivå; det är inte ljudtrycket vid kudden. Xiaomis ≤58 dB(A) saknar här tillräckliga mätvillkor för samma jämförelse. Blanda inte sådana värden med ett marknadsfört minimum. Bildrättigheter, butiksmatchning och flera modellers specifikationer återstår.",
  sources: [
    { id: "F1", title: "Midea DE – FZ10-17JR", url: "https://www.midea.com/de/klimatisieren-heizen/ventilatoren-luftkuehler/turmventilator-fz10-17jr.fz10-17jr", checkedAt: "2026-09-08", supports: "Modell, EAN, mått, tre hastigheter, timer, fjärrkontroll, spänning och angiven ljudeffektnivå. Inte ett jämförande sovrumstest." },
    { id: "F2", title: "Xiaomi Singapore – Mi Smart Standing Fan 2 Lite, specifikation", url: "https://www.mi.com/sg/product/mi-smart-standing-fan-2-lite/specs/", checkedAt: "2026-09-08", supports: "JLLDS01XY, AC-motor, Wi-Fi 2,4 GHz, spänning och angivet ljudvärde. Styrker inte svensk butiksversion eller appregion." },
    { id: "F3", title: "Dreo DE – TF518", url: "https://de.dreo.com/products/turmventilator-518", checkedAt: "2026-09-08", supports: "Sidan gäller TF518. Den används för att synliggöra modellskillnaden, inte för att överföra specifikationer till katalogens T1." },
    { id: "F4", title: "Katalogens Dreo-listning – ej läst", url: "https://www.amazon.se/dp/B08PDDSDHY", checkedAt: "2026-09-08", status: "unavailable", supports: "Läsningen blockerades. Ingen specifikation, lagerstatus eller variant har verifierats från denna sida." },
    { id: "F5", title: "Katalogens Midea MFS400-listning – ej läst", url: "https://www.amazon.se/dp/B0CPSPXN9W", checkedAt: "2026-09-08", status: "unavailable", supports: "Läsningen blockerades. Namnet är en befintlig kataloguppgift, inte en verifierad modellmatchning." },
    { id: "F6", title: "Katalogens Honeywell-listning – ej läst", url: "https://www.amazon.se/dp/B003KHJO6G", checkedAt: "2026-09-08", status: "unavailable", supports: "Läsningen blockerades. Inga funktioner eller ljudnivåer verifierades från denna sida." },
  ],
};
