import type { ProductCategorySlug } from "@/lib/products";
import { waveComparisonEntries } from "@/lib/wave-content";

export type ComparisonEntry = {
  slug: string;
  title: string;
  shortTitle: string;
  category: ProductCategorySlug;
  categoryLabel: string;
  href: string;
  description: string;
  productSlugs: string[];
  badges: string[];
};

export const comparisonEntries: readonly ComparisonEntry[] = [
  ...waveComparisonEntries,
  {
    slug: "snigelslem-eller-hyaluronsyra",
    title: "Snigelslem eller hyaluronsyra?",
    shortTitle: "Snigelslem eller hyaluronsyra",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/snigelslem-eller-hyaluronsyra",
    description: "Närande, mjukgörande K-beauty-fukt mot en lätt hyaluronsyra-boost under kräm.",
    productSlugs: ["cosrx-snail-mucin-essence","minimalist-hyaluronsyra-serum"],
    badges: ["Återfuktning","Närande vs lätt","K-beauty"],
  },
  {
    slug: "vitamin-c-eller-niacinamid",
    title: "Vitamin C eller niacinamid?",
    shortTitle: "Vitamin C eller niacinamid",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/vitamin-c-eller-niacinamid",
    description: "Lyster och glow med vitamin C mot en mild, balanserande allrounder med niacinamid.",
    productSlugs: ["la-roche-posay-vitamin-c10-serum","inkey-niacinamide-serum"],
    badges: ["Serum","Lyster vs balans","Hudvård"],
  },
  {
    slug: "oronproppar-eller-white-noise",
    title: "Öronproppar eller white noise?",
    shortTitle: "Öronproppar eller white noise",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/oronproppar-eller-white-noise",
    description: "Dämpa ljudet med öronproppar mot att maskera störande ljud med ett jämnt sömnljud.",
    productSlugs: ["loop-oronproppar","magicteam-white-noise"],
    badges: ["Bättre sömn","Dämpa vs maskera","Avslappning"],
  },
  {
    slug: "massagepistol-eller-spikmatta",
    title: "Massagepistol eller spikmatta?",
    shortTitle: "Massagepistol eller spikmatta",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/massagepistol-eller-spikmatta",
    description: "Aktiv, riktad muskelbearbetning efter träning mot passiv avslappning på kvällen.",
    productSlugs: ["beurer-mg-99-massagepistol","mattibi-spikmatta"],
    badges: ["Återhämtning","Aktiv vs passiv","Avslappning"],
  },
  {
    slug: "ipl-eller-epilator",
    title: "IPL eller epilator?",
    shortTitle: "IPL eller epilator",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/ipl-eller-epilator",
    description: "Minskad hårväxt på sikt med ljuspulser mot slät hud i veckor direkt.",
    productSlugs: ["braun-ipl-pro5","braun-silk-epil-9"],
    badges: ["Långvarig hårborttagning","Ljus vs mekaniskt","Skönhet"],
  },
  {
    slug: "luftfuktare-eller-luftrenare",
    title: "Luftfuktare eller luftrenare?",
    shortTitle: "Luftfuktare eller luftrenare",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/luftfuktare-eller-luftrenare",
    description: "Mer fukt till torr luft mot renare luft med mindre damm och partiklar.",
    productSlugs: ["levoit-luftfuktare","levoit-core-200s-luftrenare"],
    badges: ["Inomhusklimat","Fukt vs renare luft","Smart hem"],
  },
  {
    slug: "handflakt-eller-bordsflakt",
    title: "Handfläkt eller bordsfläkt?",
    shortTitle: "Handfläkt eller bordsfläkt",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/handflakt-eller-bordsflakt",
    description: "Bärbar svalka på språng mot en stadig fläkt vid skrivbordet.",
    productSlugs: ["jisulife-handflakt","xiaomi-bordsflakt"],
    badges: ["Svalka","Bärbar vs på plats","Sommar"],
  },
  {
    slug: "billaddare-eller-powerbank",
    title: "Billaddare eller powerbank?",
    shortTitle: "Billaddare eller powerbank",
    category: "resa",
    categoryLabel: "Resa",
    href: "/sommar/resa/billaddare-eller-powerbank",
    description: "Snabb laddning i bilen medan du kör mot ström överallt även utan uttag.",
    productSlugs: ["iniu-billaddare","anker-zolo-powerbank"],
    badges: ["Ladda på resan","I bilen vs överallt","Resa"],
  },
  {
    slug: "hangande-necessar-eller-genomskinlig-necessar",
    title: "Hängande necessär eller genomskinlig necessär?",
    shortTitle: "Hängande eller genomskinlig necessär",
    category: "resa",
    categoryLabel: "Resa",
    href: "/sommar/resa/hangande-necessar-eller-genomskinlig-necessar",
    description: "Häng-och-nå-allt-ordning på hotellbadrummet mot en genomskinlig necessär som är smidig i säkerhetskontrollen.",
    productSlugs: ["narwey-hangande-necessar","traxenta-necessar"],
    badges: ["Ordning på resan","Hänga vs se igenom","Resa"],
  },
  {
    slug: "press-on-eller-gelnaglar",
    title: "Press-on naglar eller gelnaglar hemma?",
    shortTitle: "Press-on eller gelnaglar",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/press-on-eller-gelnaglar",
    description: "Snabb manikyr på minuter mot hållbara gelnaglar som sitter i veckor.",
    productSlugs: ["press-on-naglar","beurer-mp48-nagellampa"],
    badges: ["Naglar hemma","Snabbt vs hållbart","Ung"],
  },
  {
    slug: "epilator-eller-rakhyvel",
    title: "Epilator eller rakhyvel?",
    shortTitle: "Epilator eller rakhyvel",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/epilator-eller-rakhyvel",
    description: "Slät hud i veckor med roten borta mot snabb, smärtfri rakning här och nu.",
    productSlugs: ["braun-silk-epil-9","merkur-safety-razor"],
    badges: ["Hårborttagning","Slät längre vs smärtfritt","Vardag"],
  },
  {
    slug: "tornflakt-eller-bordsflakt",
    title: "Tornfläkt eller bordsfläkt?",
    shortTitle: "Tornfläkt eller bordsfläkt",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/tornflakt-eller-bordsflakt",
    description: "Bred svalka för hela rummet mot riktad punktkyla precis där du sitter.",
    productSlugs: ["midea-fz10-tornflakt","xiaomi-bordsflakt"],
    badges: ["Svalka","Hela rummet vs punktkyla","Sommar"],
  },
  {
    slug: "st-tropez-eller-bondi-sands",
    title: "St.Tropez eller Bondi Sands?",
    shortTitle: "St.Tropez eller Bondi Sands",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/st-tropez-eller-bondi-sands",
    description: "Naturlig, justerbar färg med mest kontroll mot en färgad mousse som är enklast att lägga jämnt.",
    productSlugs: ["st-tropez-self-tan-express","bondi-sands-mousse"],
    badges: ["Brun utan sol","Naturlig färg","Sommar"],
  },
  {
    slug: "cerave-eller-cetaphil",
    title: "CeraVe eller Cetaphil?",
    shortTitle: "CeraVe eller Cetaphil",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/cerave-eller-cetaphil",
    description: "Återfuktande ceramid-rengöring för torr hud mot extra mild rengöring för känslig hud.",
    productSlugs: ["cerave-hydrating-cleanser","cetaphil-gentle-cleanser"],
    badges: ["Mild rengöring","Känslig hud","Vardag"],
  },
  {
    slug: "packkuber-eller-kompressionspasar",
    title: "Packkuber eller kompressionspåsar?",
    shortTitle: "Packkuber eller kompressionspåsar",
    category: "resa",
    categoryLabel: "Resa",
    href: "/sommar/resa/packkuber-eller-kompressionspasar",
    description: "Ordning och överblick mot maximal platsbesparing för skrymmande plagg.",
    productSlugs: ["travel-dude-packkuber","myhodo-kompressionspase"],
    badges: ["Ordning","Spara plats","Resa"],
  },
  {
    slug: "powerbank-eller-vaggladdare",
    title: "Powerbank eller väggladdare?",
    shortTitle: "Powerbank eller väggladdare",
    category: "resa",
    categoryLabel: "Resa",
    href: "/sommar/resa/powerbank-eller-vaggladdare",
    description: "Ström på språng utan uttag mot snabb laddning av flera enheter vid uttaget.",
    productSlugs: ["anker-zolo-powerbank","anker-735-vaggladdare"],
    badges: ["Ström på språng","Ladda flera","Resa"],
  },
  {
    slug: "dreo-cruiser-pro-eller-honeywell-ht900e",
    title: "Dreo Cruiser Pro eller Honeywell HT900E?",
    shortTitle: "Dreo eller Honeywell",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/dreo-cruiser-pro-eller-honeywell-ht900e",
    description:
      "Tyst tornfläkt för hela rummet mot kompakt kraftfläkt för riktad punktkyla.",
    productSlugs: ["dreo-cruiser-pro-tornflakt", "honeywell-turboforce-ht900e"],
    badges: ["Tyst i sovrummet", "Kraftfull", "Sommar"],
  },
  {
    slug: "traningsband",
    title: "Långa träningsband vs JAKKOFOXX loop-band",
    shortTitle: "Träningsband",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/traningsband",
    description:
      "Långa band i naturlatex för helkropp mot loop-band för ben och rumpa.",
    productSlugs: ["traningsband-4-nivaer", "jakkofoxx-loopband"],
    badges: ["Helkropp", "Ben & rumpa", "Mest beprövad"],
  },
  {
    slug: "kettlebell",
    title: "Amazon Basics vs PROIRON mjuk kettlebell",
    shortTitle: "Kettlebell",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/kettlebell",
    description:
      "Gjutjärn för mest värde mot mjuk kettlebell för golv, ljud och nybörjare.",
    productSlugs: [
      "amazon-basics-gjutjarns-kettlebell",
      "proiron-mjuk-kettlebell",
    ],
    badges: ["Mest värde", "Golvvänligt", "Nybörjarvänligt"],
  },
  {
    slug: "hantlar",
    title: "PROIRON neoprenhantlar vs SONGMICS hantelset",
    shortTitle: "Hantlar",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/hantlar",
    description:
      "Ett enkelt par i rätt vikt mot ett färdigt startset med ställning.",
    productSlugs: ["proiron-neoprenhantlar", "songmics-hantelset-med-stallning"],
    badges: ["Mest beprövad", "Set + ställning", "Hemmaträning"],
  },
  {
    slug: "yogamatta",
    title: "ProSourceFit 13 mm vs YOGATI TPE yogamatta",
    shortTitle: "Yogamatta",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/yogamatta",
    description:
      "Extra komfort för pilates och golvövningar mot bättre grepp för yoga.",
    productSlugs: [
      "prosourcefit-extra-tjock-yogamatta",
      "yogati-tpe-yogamatta",
    ],
    badges: ["13 mm komfort", "Bra grepp", "Balans"],
  },
  {
    slug: "foam-roller",
    title: "BODYMATE CARE vs Elvire Deep Tissue foam roller",
    shortTitle: "Foam roller",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/foam-roller",
    description:
      "En enkel slät rulle med ryggränna mot ett komplett texturerat återhämtningsset.",
    productSlugs: [
      "bodymate-foam-roller-care",
      "elvire-deep-tissue-massageset",
    ],
    badges: ["Mest värde", "Komplett set", "Deep-tissue"],
  },
  {
    slug: "massagepistol",
    title: "Beurer MG 99 vs BDBKMG massagepistol",
    shortTitle: "Massagepistol",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/massagepistol",
    description:
      "Kompakt märkesval mot fler lägen och mer funktioner för pengarna.",
    productSlugs: ["beurer-mg-99-massagepistol", "bdbkmg-massagepistol"],
    badges: ["Känt märke", "99 lägen", "Återhämtning"],
  },
  {
    slug: "plattang",
    title: "Remington S8540 vs Remington Mini S2880",
    shortTitle: "Plattång",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/plattang",
    description:
      "Beprövad vardagsplattång mot ett ärligt begränsat reseval.",
    productSlugs: ["remington-s8540-plattang", "remington-mini-s2880-plattang"],
    badges: ["Beprövat val", "Resvänlig", "Hårstyling"],
  },
  {
    slug: "epilator",
    title: "Panasonic ES-EY30 vs Braun Silk-épil 9",
    shortTitle: "Epilator",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/epilator",
    description:
      "Prisvärt premiumval mot ett dyrare paket med fler tillbehör.",
    productSlugs: ["panasonic-es-ey30-epilator", "braun-silk-epil-9"],
    badges: ["Wet/Dry", "Premiumval", "Lenare resultat"],
  },
  {
    slug: "hartork",
    title: "Remington PROluxe vs Beurer HC 25 hårtork",
    shortTitle: "Hårtork",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/hartork",
    description:
      "Salongskraft hemma mot en lättare rese- och budgethårtork.",
    productSlugs: ["remington-proluxe-ac9140-hartork", "beurer-hc-25-hartork"],
    badges: ["2400 W", "Resvänlig", "Budgetval"],
  },
  {
    slug: "locktang",
    title: "BaByliss C325E vs TYMO CURLPRO locktång",
    shortTitle: "Locktång",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/locktang",
    description:
      "Manuellt värdeval för stora lockar mot automatisk premiumstyling.",
    productSlugs: ["babyliss-c325e-locktang", "tymo-curlpro-locktang"],
    badges: ["Mest värde", "Automatisk", "Stora lockar"],
  },
  {
    slug: "varmluftsborste",
    title: "BaByliss AS126E vs Remington AS7100 varmluftsborste",
    shortTitle: "Varmluftsborste",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/varmluftsborste",
    description:
      "Mångsidig 4-i-1 för volym mot billigare styling för kort hår.",
    productSlugs: [
      "babyliss-as126e-varmluftsborste",
      "remington-as7100-varmluftsborste",
    ],
    badges: ["4-i-1", "Budgetval", "Kort hår"],
  },
  {
    slug: "platta-eller-locka",
    title: "Platta eller locka?",
    shortTitle: "Platta eller locka?",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/platta-eller-locka",
    description:
      "Slätt, polerat och mjuka vågor mot definierade klassiska lockar.",
    productSlugs: ["remington-s8540-plattang", "babyliss-c325e-locktang"],
    badges: ["Rakt & vågor", "Definierade lockar", "Mångsidig"],
  },
  {
    slug: "varmluftsborste-eller-fon",
    title: "Varmluftsborste eller vanlig fön?",
    shortTitle: "Varmluftsborste eller fön",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/varmluftsborste-eller-fon",
    description:
      "Torka och styla i samma moment mot ren, kraftfull torkning.",
    productSlugs: [
      "babyliss-as126e-varmluftsborste",
      "remington-proluxe-ac9140-hartork",
    ],
    badges: ["Torka + styla", "Mest torkkraft", "Volym"],
  },
  {
    slug: "sommarglow-utan-sol",
    title: "Sommarglow utan sol",
    shortTitle: "Sommarglow utan sol",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/sommarglow-utan-sol",
    description:
      "Hållbar självbruna som utvecklas mot flexibel, tvättbar glow.",
    productSlugs: ["st-tropez-self-tan-express", "elf-skin-bronzing-drops"],
    badges: ["Håller i dagar", "Tvättbar glow", "Sommar"],
  },
  {
    slug: "harolja-eller-varmeskydd",
    title: "Hårolja eller värmeskydd?",
    shortTitle: "Hårolja eller värmeskydd",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/harolja-eller-varmeskydd",
    description:
      "Glans och mjukhet för torrt hår mot skydd före värmestyling.",
    productSlugs: ["moroccanoil-harolja", "loreal-elvital-varmeskydd"],
    badges: ["Skyddar vid värme", "Glans & mjukhet", "Sommarvård"],
  },
  {
    slug: "varmluftsborste-eller-plattang",
    title: "Varmluftsborste eller plattång?",
    shortTitle: "Varmluftsborste eller plattång",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/varmluftsborste-eller-plattang",
    description:
      "Volym och böj i ett steg mot slätt, polerat och mer mångsidigt.",
    productSlugs: ["babyliss-as126e-varmluftsborste", "remington-s8540-plattang"],
    badges: ["Allt-i-ett", "Slätt & polerat", "Volym"],
  },
  {
    slug: "aftersun-eller-aloe-vera",
    title: "Aftersun eller aloe vera?",
    shortTitle: "Aftersun eller aloe vera",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/aftersun-eller-aloe-vera",
    description:
      "Mjukgörande after sun-lotion för kroppen mot en lätt, svalkande aloe vera-gel.",
    productSlugs: ["nivea-sun-after-sun-lotion", "naissance-aloe-vera-gel"],
    badges: ["Svalkar", "Återfuktar", "Sommar"],
  },
  {
    slug: "harinpackning-eller-harolja",
    title: "Hårinpackning eller hårolja?",
    shortTitle: "Hårinpackning eller hårolja",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/harinpackning-eller-harolja",
    description:
      "Intensiv inpackning som sköljs ur mot glansgivande leave-in-olja.",
    productSlugs: ["loreal-absolut-repair", "moroccanoil-harolja"],
    badges: ["Djup kur", "Glans & mjukhet", "Sommarvård"],
  },
  {
    slug: "kettlebell-eller-hantlar",
    title: "Kettlebell eller hantlar?",
    shortTitle: "Kettlebell eller hantlar",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/kettlebell-eller-hantlar",
    description:
      "Ett mångsidigt redskap för svingar mot ett komplett hantelset med ställning.",
    productSlugs: [
      "amazon-basics-gjutjarns-kettlebell",
      "songmics-hantelset-med-stallning",
    ],
    badges: ["Helkropp", "Set + ställning", "Hemmaträning"],
  },
  {
    slug: "foam-roller-eller-massagepistol",
    title: "Foam roller eller massagepistol?",
    shortTitle: "Foam roller eller massagepistol",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/foam-roller-eller-massagepistol",
    description:
      "Enkel återhämtning för stora muskelgrupper mot riktad vibration på enskilda punkter.",
    productSlugs: ["bodymate-foam-roller-care", "beurer-mg-99-massagepistol"],
    badges: ["Återhämtning", "Billigast", "Riktad"],
  },
  {
    slug: "mini-projektor-eller-stjarnprojektor",
    title: "Mini-projektor eller stjärnprojektor?",
    shortTitle: "Mini- eller stjärnprojektor",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/mini-projektor-eller-stjarnprojektor",
    description:
      "Bärbar bio för film på väggen mot en drömmig galaxhimmel på taket.",
    productSlugs: ["mini-projektor", "stjarnprojektor"],
    badges: ["Film på väggen", "Galaxhimmel", "Mys"],
  },
];

export function getComparisonsByCategory(category: ProductCategorySlug) {
  return comparisonEntries.filter((comparison) => comparison.category === category);
}

export function getRelatedComparisons(
  category: ProductCategorySlug,
  currentHref?: string,
) {
  return comparisonEntries
    .filter(
      (comparison) =>
        comparison.category === category && comparison.href !== currentHref,
    )
    .slice(0, 3);
}
