import type { ProductCategorySlug } from "@/lib/products";
import { waveComparisonEntries } from "@/lib/wave-content";

export type ComparisonEntry = {
  slug: string;
  title: string;
  shortTitle: string;
  category: ProductCategorySlug;
  categoryLabel: string;
  href: string;
  description: string;
  productSlugs: string[];
  badges: string[];
};

export const comparisonEntries: readonly ComparisonEntry[] = [
  ...waveComparisonEntries,
  {
    slug: "strandfilt-eller-strandhandduk",
    title: "Strandfilt eller strandhandduk?",
    shortTitle: "Strandfilt eller strandhandduk",
    category: "resa",
    categoryLabel: "Resa",
    href: "/sommar/resa/strandfilt-eller-strandhandduk",
    description: "En sandfri sittyta för sällskapet mot en mjuk handduk att torka sig med – vad ska du packa?",
    productSlugs: ["anortrek-sandfri-strandfilt","utopia-cabana-strandhandduk"],
    badges: ["Sittplats vs torkning","Sandfri bas vs komfort","Strand & bad"],
  },
  {
    slug: "kabinvaska-eller-ryggsack",
    title: "Kabinväska eller ryggsäck?",
    shortTitle: "Kabinväska eller ryggsäck",
    category: "resa",
    categoryLabel: "Resa",
    href: "/sommar/resa/kabinvaska-eller-ryggsack",
    description: "Rulla ett hårt skal eller bära en rymlig ryggsäck – vilken passar din resa?",
    productSlugs: ["cabin-max-anode-kabinvaska","taygeer-kabinryggsack"],
    badges: ["Rulla vs bära","Hårt skal vs mer plats","Handbagage"],
  },
  {
    slug: "mikrofiberhandduk-eller-frottehandduk",
    title: "Mikrofiberhandduk eller frottéhandduk?",
    shortTitle: "Mikrofiberhandduk eller frottéhandduk",
    category: "resa",
    categoryLabel: "Resa",
    href: "/sommar/resa/mikrofiberhandduk-eller-frottehandduk",
    description: "Packvänlig snabbtork mot mjuk, sugande bomull – vilken handduk ska du ta med?",
    productSlugs: ["fit-flip-mikrofiberhandduk","utopia-cabana-strandhandduk"],
    badges: ["Packvänligt vs komfort","Snabbtork vs mjukhet","Resa & strand"],
  },
  {
    slug: "bha-eller-aha-bha-peeling",
    title: "BHA eller AHA/BHA-peeling?",
    shortTitle: "BHA eller AHA/BHA-peeling",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/bha-eller-aha-bha-peeling",
    description: "Porrengörande salicylsyra för oljig hud mot en allround AHA/BHA-peeling för glow.",
    productSlugs: ["paulas-choice-2-bha","purest-aha-bha-peeling"],
    badges: ["Exfoliering","Porer vs allround","Hudvård"],
  },
  {
    slug: "bakuchiol-eller-niacinamid",
    title: "Bakuchiol eller niacinamid?",
    shortTitle: "Bakuchiol eller niacinamid",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/bakuchiol-eller-niacinamid",
    description: "Ett skonsamt, växtbaserat och slätande alternativ mot en balanserande allrounder.",
    productSlugs: ["celdyque-bakuchiol-serum","inkey-niacinamide-serum"],
    badges: ["Serum","Skonsamt vs balans","Hudvård"],
  },
  {
    slug: "stepbrada-eller-studsmatta",
    title: "Stepbräda eller studsmatta?",
    shortTitle: "Stepbräda eller studsmatta",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/stepbrada-eller-studsmatta",
    description: "Justerbar benträning med stepbräda mot skonsam, lekfull studsträning.",
    productSlugs: ["reebok-stepbrada","dh-fitlife-studsmatta"],
    badges: ["Kondition hemma","Steg vs studs","Kul"],
  },
  {
    slug: "lyftremmar-eller-traningshandskar",
    title: "Lyftremmar eller träningshandskar?",
    shortTitle: "Lyftremmar eller träningshandskar",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/lyftremmar-eller-traningshandskar",
    description: "Avlasta greppet vid tunga lyft med remmar mot att skydda händerna med träningshandskar.",
    productSlugs: ["fitgriff-lifting-straps","ihuan-traningshandskar"],
    badges: ["Gymtillbehör","Avlasta grepp vs skydda händer","Styrka"],
  },
  {
    slug: "balansplatta-eller-gymboll",
    title: "Balansplatta eller gymboll?",
    shortTitle: "Balansplatta eller gymboll",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/balansplatta-eller-gymboll",
    description: "Fokuserad balansträning på liten yta mot en mångsidig gymboll för bål och stabilitet.",
    productSlugs: ["gorilla-balansplatta","gorilla-gymboll"],
    badges: ["Balans & bål","Kompakt vs mångsidig","Stabilitet"],
  },
  {
    slug: "pilatesring-eller-yogablock",
    title: "Pilatesring eller yogablock?",
    shortTitle: "Pilatesring eller yogablock",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/pilatesring-eller-yogablock",
    description: "Lätt motstånd för pilates mot stöd och stabilitet för yoga.",
    productSlugs: ["g5-pilatesring","bodymate-yogablock"],
    badges: ["Pilates & yoga","Motstånd vs stöd","Nybörjare"],
  },
  {
    slug: "rosmarinolja-eller-scalp-scrub",
    title: "Rosmarinolja eller scalp scrub?",
    shortTitle: "Rosmarinolja eller scalp scrub",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/rosmarinolja-eller-scalp-scrub",
    description: "Vårda och massera hårbotten med rosmarinolja mot att exfoliera och rengöra den med en scalp scrub.",
    productSlugs: ["mielle-rosemary-oil","inkey-scalp-scrub"],
    badges: ["Hårbotten","Vårda vs rengöra","Hår"],
  },
  {
    slug: "ansiktstrimmer-eller-rakapparat-dam",
    title: "Ansiktstrimmer eller rakapparat för dam?",
    shortTitle: "Ansiktstrimmer eller rakapparat",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/ansiktstrimmer-eller-rakapparat-dam",
    description: "Exakt formning av fina hår mot snabb, skonsam rakning av större ytor.",
    productSlugs: ["philips-ansiktstrimmer","philips-rakapparat-dam"],
    badges: ["Ansiktshår","Exakt vs snabbt","Skonsamt"],
  },
  {
    slug: "texturspray-eller-volympuder",
    title: "Texturspray eller volympuder?",
    shortTitle: "Texturspray eller volympuder",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/texturspray-eller-volympuder",
    description: "Grepp och matt struktur i hela håret mot snabbt rotlyft där håret är plattast.",
    productSlugs: ["maria-nila-texturspray","osis-volympuder"],
    badges: ["Hårstyling","Struktur vs lyft","Volym"],
  },
  {
    slug: "leave-in-eller-harolja",
    title: "Leave-in eller hårolja?",
    shortTitle: "Leave-in eller hårolja",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/leave-in-eller-harolja",
    description: "Lätt återfuktning och utredning med leave-in mot glans och antifriss med hårolja.",
    productSlugs: ["cantu-leave-in-conditioner","moroccanoil-harolja"],
    badges: ["Hårvård","Återfukta vs glans","Vardag"],
  },
  {
    slug: "solnedgangslampa-eller-stjarnprojektor",
    title: "Solnedgångslampa eller stjärnprojektor?",
    shortTitle: "Solnedgångslampa eller stjärnprojektor",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/solnedgangslampa-eller-stjarnprojektor",
    description: "Varmt, stilrent solnedgångsljus mot en drömlik, lekfull stjärnhimmel i taket.",
    productSlugs: ["solnedgangslampa","stjarnprojektor"],
    badges: ["Stämningsljus","Solnedgång vs stjärnhimmel","Mys"],
  },
  {
    slug: "varmedyna-eller-massagekudde",
    title: "Värmedyna eller massagekudde?",
    shortTitle: "Värmedyna eller massagekudde",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/varmedyna-eller-massagekudde",
    description: "Mjuk, avslappnande värme mot aktiv knådning av spända muskler.",
    productSlugs: ["beurer-varmedyna","renpho-massagekudde"],
    badges: ["Avslappning","Värme vs knådning","Återhämtning"],
  },
  {
    slug: "bikinitrimmer-eller-rakhyvel",
    title: "Bikinitrimmer eller rakhyvel?",
    shortTitle: "Bikinitrimmer eller rakhyvel",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/bikinitrimmer-eller-rakhyvel",
    description: "Skonsam trimning med minimal irritation mot en helt slät rakning.",
    productSlugs: ["braun-bikinitrimmer","merkur-safety-razor"],
    badges: ["Bikinilinjen","Trimma vs slätt","Skonsamt"],
  },
  {
    slug: "wake-up-light-eller-solnedgangslampa",
    title: "Wake-up light eller solnedgångslampa?",
    shortTitle: "Wake-up light eller solnedgångslampa",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/wake-up-light-eller-solnedgangslampa",
    description: "En mjukare väckning på morgonen mot varmt, gyllene kvällsmys.",
    productSlugs: ["philips-wake-up-light","solnedgangslampa"],
    badges: ["Ljus & stämning","Morgon vs kväll","Sömn & mys"],
  },
  {
    slug: "satinmossa-eller-sidenorngott",
    title: "Satinmössa eller sidenörngott?",
    shortTitle: "Satinmössa eller sidenörngott",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/satinmossa-eller-sidenorngott",
    description: "Samla och skydda frisyren med en satinmössa mot en len sidenyta som är snäll mot hår och hud.",
    productSlugs: ["cantu-satin-bonnet","silkesorngott-mullbarssilke"],
    badges: ["Hårvård natten","Samla vs fritt","Mys"],
  },
  {
    slug: "tangle-teezer-eller-harborste",
    title: "Tangle Teezer eller vanlig hårborste?",
    shortTitle: "Tangle Teezer eller hårborste",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/tangle-teezer-eller-harborste",
    description: "En kompakt borste som glider genom tovor mot en Wet Brush som är extra snäll mot blött hår.",
    productSlugs: ["tangle-teezer-original","wet-brush-original"],
    badges: ["Håret","Reder ut tovor","Vardag"],
  },
  {
    slug: "heatless-lockar-eller-locktang",
    title: "Heatless lockar eller locktång?",
    shortTitle: "Heatless lockar eller locktång",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/heatless-lockar-eller-locktang",
    description: "Skonsamma lockar utan värme mot snabba, exakta lockar med locktång.",
    productSlugs: ["kitsch-heatless-curls","babyliss-c325e-locktang"],
    badges: ["Lockar","Utan värme vs snabbt","Ung"],
  },
  {
    slug: "aromdiffuser-eller-luftfuktare",
    title: "Aromdiffuser eller luftfuktare?",
    shortTitle: "Aromdiffuser eller luftfuktare",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/aromdiffuser-eller-luftfuktare",
    description: "Doft och mysig stämning med en aromdiffuser mot fukt till torr luft med en luftfuktare.",
    productSlugs: ["salking-aromadiffuser","levoit-luftfuktare"],
    badges: ["Inomhusklimat","Doft vs fukt","Mys"],
  },
  {
    slug: "termos-eller-vattenflaska",
    title: "Termos eller vattenflaska?",
    shortTitle: "Termos eller vattenflaska",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/termos-eller-vattenflaska",
    description: "Håll drycken kall eller varm i timmar mot en flaska som peppar dig att dricka mer.",
    productSlugs: ["stanley-termos","twsoul-vattenflaska"],
    badges: ["Drick mer","Håll temperatur vs påminnelse","Vardag"],
  },
  {
    slug: "yogablock-eller-yogabalte",
    title: "Yogablock eller yogabälte?",
    shortTitle: "Yogablock eller yogabälte",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/yogablock-eller-yogabalte",
    description: "Stöd och höjd med ett yogablock mot längre räckvidd i stretch med ett yogabälte.",
    productSlugs: ["bodymate-yogablock","bodymate-yogabalte"],
    badges: ["Yoga","Stöd vs räckvidd","Nybörjare"],
  },
  {
    slug: "maghjul-eller-core-slider",
    title: "Maghjul eller core slider?",
    shortTitle: "Maghjul eller core slider",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/maghjul-eller-core-slider",
    description: "En intensiv, tydlig magövning mot mångsidiga glidövningar för bål och helkropp.",
    productSlugs: ["amonax-maghjul","gorilla-core-slider"],
    badges: ["Bål & mage","Intensivt vs mångsidigt","Kroppsvikt"],
  },
  {
    slug: "rengoringsolja-eller-micellarvatten",
    title: "Rengöringsolja eller micellärvatten?",
    shortTitle: "Rengöringsolja eller micellärvatten",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/rengoringsolja-eller-micellarvatten",
    description: "Djup borttagning av mycket och vattenfast smink mot snabb, skonsam rengöring utan sköljning.",
    productSlugs: ["some-by-mi-cleansing-oil","bioderma-sensibio-h2o"],
    badges: ["Rengöring","Djup vs snabb","Hudvård"],
  },
  {
    slug: "lappmask-eller-lappolja",
    title: "Läppmask eller läppolja?",
    shortTitle: "Läppmask eller läppolja",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/lappmask-eller-lappolja",
    description: "Djup nattlig återfuktning med läppmask mot glansig dagvård med lyster med läppolja.",
    productSlugs: ["laneige-lip-sleeping-mask","dior-lip-glow-oil"],
    badges: ["Läppvård","Natt vs dag","Glow"],
  },
  {
    slug: "vaxremsor-eller-rakhyvel",
    title: "Vaxremsor eller rakhyvel?",
    shortTitle: "Vaxremsor eller rakhyvel",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/vaxremsor-eller-rakhyvel",
    description: "Slät hud i veckor med roten borta mot snabb, smärtfri rakning här och nu.",
    productSlugs: ["veet-vaxremsor","merkur-safety-razor"],
    badges: ["Hårborttagning","Slät längre vs smärtfritt","Vardag"],
  },
  {
    slug: "pull-up-bar-eller-gymnastikringar",
    title: "Pull-up bar eller gymnastikringar?",
    shortTitle: "Pull-up bar eller gymnastikringar",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/pull-up-bar-eller-gymnastikringar",
    description: "Enkel pull-up-träning i dörrkarmen mot mer utmanande ringträning för hela överkroppen.",
    productSlugs: ["iron-gym-pull-up-bar","gorilla-gymnastikringar"],
    badges: ["Överkropp hemma","Enkelt vs utmanande","Kroppsvikt"],
  },
  {
    slug: "studsmatta-eller-hopprep",
    title: "Studsmatta eller hopprep?",
    shortTitle: "Studsmatta eller hopprep",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/studsmatta-eller-hopprep",
    description: "Skonsam, kul studsträning mot billig, platssnål hoppträning för kondition hemma.",
    productSlugs: ["dh-fitlife-studsmatta","portentum-hopprep"],
    badges: ["Kondition hemma","Skonsamt vs effektivt","Kul"],
  },
  {
    slug: "hantlar-eller-gummiband",
    title: "Hantlar eller gummiband?",
    shortTitle: "Hantlar eller gummiband",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/hantlar-eller-gummiband",
    description: "Fast, ökbart motstånd med hantlar mot följsamt, platssnålt motstånd med gummiband.",
    productSlugs: ["proiron-neoprenhantlar","elvire-miniband"],
    badges: ["Hemmaträning","Fast vikt vs följsamt","Nybörjare"],
  },
  {
    slug: "luftkylare-eller-flakt",
    title: "Luftkylare eller fläkt?",
    shortTitle: "Luftkylare eller fläkt",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/luftkylare-eller-flakt",
    description: "En fuktad, extra sval bris på nära håll mot en enkel, stark luftström.",
    productSlugs: ["beurer-luftkylare","xiaomi-bordsflakt"],
    badges: ["Svalka","Bris vs fuktad kyla","Sommar"],
  },
  {
    slug: "bronzer-eller-brun-utan-sol",
    title: "Bronzer eller brun utan sol?",
    shortTitle: "Bronzer eller brun utan sol",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/bronzer-eller-brun-utan-sol",
    description: "En tvättbar glow för dagen mot en verklig färg som håller i flera dagar.",
    productSlugs: ["elf-skin-bronzing-drops","bondi-sands-mousse"],
    badges: ["Solkysst utan sol","Direkt vs håller","Sommar"],
  },
  {
    slug: "brynserum-eller-brynlaminering",
    title: "Brynserum eller brynlaminering?",
    shortTitle: "Brynserum eller brynlaminering",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/brynserum-eller-brynlaminering",
    description: "En enkel daglig rutin för fylligare uttryck mot en fyllig, uppborstad look direkt.",
    productSlugs: ["nanobrow-brynserum","sorella-brynlaminering"],
    badges: ["Fylligare bryn","Långsiktigt vs direkt","Bryn"],
  },
  {
    slug: "sminksvamp-eller-sminkborste",
    title: "Sminksvamp eller sminkborste?",
    shortTitle: "Sminksvamp eller sminkborste",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/sminksvamp-eller-sminkborste",
    description: "Naturlig, hudlik finish med svamp mot snabb, jämn täckning med borste.",
    productSlugs: ["real-techniques-svamp","real-techniques-borstar"],
    badges: ["Foundation","Naturlig vs täckande","Makeup"],
  },
  {
    slug: "foot-peel-eller-elektrisk-fotfil",
    title: "Foot peel mask eller elektrisk fotfil?",
    shortTitle: "Foot peel eller elektrisk fotfil",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/foot-peel-eller-elektrisk-fotfil",
    description: "Djup flagning över ett par veckor mot direkt, kontrollerad filning av hård hud.",
    productSlugs: ["plantifique-foot-peel","vxdoirk-elektrisk-fotfil"],
    badges: ["Sandalfina fötter","Flagnar vs filar","Sommar"],
  },
  {
    slug: "snigelslem-eller-hyaluronsyra",
    title: "Snigelslem eller hyaluronsyra?",
    shortTitle: "Snigelslem eller hyaluronsyra",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/snigelslem-eller-hyaluronsyra",
    description: "Närande, mjukgörande K-beauty-fukt mot en lätt hyaluronsyra-boost under kräm.",
    productSlugs: ["cosrx-snail-mucin-essence","minimalist-hyaluronsyra-serum"],
    badges: ["Återfuktning","Närande vs lätt","K-beauty"],
  },
  {
    slug: "vitamin-c-eller-niacinamid",
    title: "Vitamin C eller niacinamid?",
    shortTitle: "Vitamin C eller niacinamid",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/vitamin-c-eller-niacinamid",
    description: "Lyster och glow med vitamin C mot en mild, balanserande allrounder med niacinamid.",
    productSlugs: ["la-roche-posay-vitamin-c10-serum","inkey-niacinamide-serum"],
    badges: ["Serum","Lyster vs balans","Hudvård"],
  },
  {
    slug: "oronproppar-eller-white-noise",
    title: "Öronproppar eller white noise?",
    shortTitle: "Öronproppar eller white noise",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/oronproppar-eller-white-noise",
    description: "Dämpa ljudet med öronproppar mot att maskera störande ljud med ett jämnt sömnljud.",
    productSlugs: ["loop-oronproppar","magicteam-white-noise"],
    badges: ["Bättre sömn","Dämpa vs maskera","Avslappning"],
  },
  {
    slug: "massagepistol-eller-spikmatta",
    title: "Massagepistol eller spikmatta?",
    shortTitle: "Massagepistol eller spikmatta",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/massagepistol-eller-spikmatta",
    description: "Aktiv, riktad muskelbearbetning efter träning mot passiv avslappning på kvällen.",
    productSlugs: ["beurer-mg-99-massagepistol","mattibi-spikmatta"],
    badges: ["Återhämtning","Aktiv vs passiv","Avslappning"],
  },
  {
    slug: "ipl-eller-epilator",
    title: "IPL eller epilator?",
    shortTitle: "IPL eller epilator",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/ipl-eller-epilator",
    description: "Minskad hårväxt på sikt med ljuspulser mot slät hud i veckor direkt.",
    productSlugs: ["braun-ipl-pro5","braun-silk-epil-9"],
    badges: ["Långvarig hårborttagning","Ljus vs mekaniskt","Skönhet"],
  },
  {
    slug: "luftfuktare-eller-luftrenare",
    title: "Luftfuktare eller luftrenare?",
    shortTitle: "Luftfuktare eller luftrenare",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/luftfuktare-eller-luftrenare",
    description: "Mer fukt till torr luft mot renare luft med mindre damm och partiklar.",
    productSlugs: ["levoit-luftfuktare","levoit-core-200s-luftrenare"],
    badges: ["Inomhusklimat","Fukt vs renare luft","Smart hem"],
  },
  {
    slug: "handflakt-eller-bordsflakt",
    title: "Handfläkt eller bordsfläkt?",
    shortTitle: "Handfläkt eller bordsfläkt",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/handflakt-eller-bordsflakt",
    description: "Bärbar svalka på språng mot en stadig fläkt vid skrivbordet.",
    productSlugs: ["jisulife-handflakt","xiaomi-bordsflakt"],
    badges: ["Svalka","Bärbar vs på plats","Sommar"],
  },
  {
    slug: "billaddare-eller-powerbank",
    title: "Billaddare eller powerbank?",
    shortTitle: "Billaddare eller powerbank",
    category: "resa",
    categoryLabel: "Resa",
    href: "/sommar/resa/billaddare-eller-powerbank",
    description: "Snabb laddning i bilen medan du kör mot ström överallt även utan uttag.",
    productSlugs: ["iniu-billaddare","anker-zolo-powerbank"],
    badges: ["Ladda på resan","I bilen vs överallt","Resa"],
  },
  {
    slug: "hangande-necessar-eller-genomskinlig-necessar",
    title: "Hängande necessär eller genomskinlig necessär?",
    shortTitle: "Hängande eller genomskinlig necessär",
    category: "resa",
    categoryLabel: "Resa",
    href: "/sommar/resa/hangande-necessar-eller-genomskinlig-necessar",
    description: "Häng-och-nå-allt-ordning på hotellbadrummet mot en genomskinlig necessär som är smidig i säkerhetskontrollen.",
    productSlugs: ["narwey-hangande-necessar","traxenta-necessar"],
    badges: ["Ordning på resan","Hänga vs se igenom","Resa"],
  },
  {
    slug: "press-on-eller-gelnaglar",
    title: "Press-on naglar eller gelnaglar hemma?",
    shortTitle: "Press-on eller gelnaglar",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/press-on-eller-gelnaglar",
    description: "Snabb manikyr på minuter mot hållbara gelnaglar som sitter i veckor.",
    productSlugs: ["press-on-naglar","beurer-mp48-nagellampa"],
    badges: ["Naglar hemma","Snabbt vs hållbart","Ung"],
  },
  {
    slug: "epilator-eller-rakhyvel",
    title: "Epilator eller rakhyvel?",
    shortTitle: "Epilator eller rakhyvel",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/epilator-eller-rakhyvel",
    description: "Slät hud i veckor med roten borta mot snabb, smärtfri rakning här och nu.",
    productSlugs: ["braun-silk-epil-9","merkur-safety-razor"],
    badges: ["Hårborttagning","Slät längre vs smärtfritt","Vardag"],
  },
  {
    slug: "tornflakt-eller-bordsflakt",
    title: "Tornfläkt eller bordsfläkt?",
    shortTitle: "Tornfläkt eller bordsfläkt",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/tornflakt-eller-bordsflakt",
    description: "Bred svalka för hela rummet mot riktad punktkyla precis där du sitter.",
    productSlugs: ["midea-fz10-tornflakt","xiaomi-bordsflakt"],
    badges: ["Svalka","Hela rummet vs punktkyla","Sommar"],
  },
  {
    slug: "st-tropez-eller-bondi-sands",
    title: "St.Tropez eller Bondi Sands?",
    shortTitle: "St.Tropez eller Bondi Sands",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/st-tropez-eller-bondi-sands",
    description: "Naturlig, justerbar färg med mest kontroll mot en färgad mousse som är enklast att lägga jämnt.",
    productSlugs: ["st-tropez-self-tan-express","bondi-sands-mousse"],
    badges: ["Brun utan sol","Naturlig färg","Sommar"],
  },
  {
    slug: "cerave-eller-cetaphil",
    title: "CeraVe eller Cetaphil?",
    shortTitle: "CeraVe eller Cetaphil",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/cerave-eller-cetaphil",
    description: "Återfuktande ceramid-rengöring för torr hud mot extra mild rengöring för känslig hud.",
    productSlugs: ["cerave-hydrating-cleanser","cetaphil-gentle-cleanser"],
    badges: ["Mild rengöring","Känslig hud","Vardag"],
  },
  {
    slug: "packkuber-eller-kompressionspasar",
    title: "Packkuber eller kompressionspåsar?",
    shortTitle: "Packkuber eller kompressionspåsar",
    category: "resa",
    categoryLabel: "Resa",
    href: "/sommar/resa/packkuber-eller-kompressionspasar",
    description: "Ordning och överblick mot maximal platsbesparing för skrymmande plagg.",
    productSlugs: ["travel-dude-packkuber","myhodo-kompressionspase"],
    badges: ["Ordning","Spara plats","Resa"],
  },
  {
    slug: "powerbank-eller-vaggladdare",
    title: "Powerbank eller väggladdare?",
    shortTitle: "Powerbank eller väggladdare",
    category: "resa",
    categoryLabel: "Resa",
    href: "/sommar/resa/powerbank-eller-vaggladdare",
    description: "Ström på språng utan uttag mot snabb laddning av flera enheter vid uttaget.",
    productSlugs: ["anker-zolo-powerbank","anker-735-vaggladdare"],
    badges: ["Ström på språng","Ladda flera","Resa"],
  },
  {
    slug: "dreo-cruiser-pro-eller-honeywell-ht900e",
    title: "Dreo Cruiser Pro eller Honeywell HT900E?",
    shortTitle: "Dreo eller Honeywell",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/dreo-cruiser-pro-eller-honeywell-ht900e",
    description:
      "Tyst tornfläkt för hela rummet mot kompakt kraftfläkt för riktad punktkyla.",
    productSlugs: ["dreo-cruiser-pro-tornflakt", "honeywell-turboforce-ht900e"],
    badges: ["Tyst i sovrummet", "Kraftfull", "Sommar"],
  },
  {
    slug: "traningsband",
    title: "Långa träningsband vs JAKKOFOXX loop-band",
    shortTitle: "Träningsband",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/traningsband",
    description:
      "Långa band i naturlatex för helkropp mot loop-band för ben och rumpa.",
    productSlugs: ["traningsband-4-nivaer", "jakkofoxx-loopband"],
    badges: ["Helkropp", "Ben & rumpa", "Mest beprövad"],
  },
  {
    slug: "kettlebell",
    title: "Amazon Basics vs PROIRON mjuk kettlebell",
    shortTitle: "Kettlebell",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/kettlebell",
    description:
      "Gjutjärn för mest värde mot mjuk kettlebell för golv, ljud och nybörjare.",
    productSlugs: [
      "amazon-basics-gjutjarns-kettlebell",
      "proiron-mjuk-kettlebell",
    ],
    badges: ["Mest värde", "Golvvänligt", "Nybörjarvänligt"],
  },
  {
    slug: "hantlar",
    title: "PROIRON neoprenhantlar vs SONGMICS hantelset",
    shortTitle: "Hantlar",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/hantlar",
    description:
      "Ett enkelt par i rätt vikt mot ett färdigt startset med ställning.",
    productSlugs: ["proiron-neoprenhantlar", "songmics-hantelset-med-stallning"],
    badges: ["Mest beprövad", "Set + ställning", "Hemmaträning"],
  },
  {
    slug: "yogamatta",
    title: "ProSourceFit 13 mm vs YOGATI TPE yogamatta",
    shortTitle: "Yogamatta",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/yogamatta",
    description:
      "Extra komfort för pilates och golvövningar mot bättre grepp för yoga.",
    productSlugs: [
      "prosourcefit-extra-tjock-yogamatta",
      "yogati-tpe-yogamatta",
    ],
    badges: ["13 mm komfort", "Bra grepp", "Balans"],
  },
  {
    slug: "foam-roller",
    title: "BODYMATE CARE vs Elvire Deep Tissue foam roller",
    shortTitle: "Foam roller",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/foam-roller",
    description:
      "En enkel slät rulle med ryggränna mot ett komplett texturerat återhämtningsset.",
    productSlugs: [
      "bodymate-foam-roller-care",
      "elvire-deep-tissue-massageset",
    ],
    badges: ["Mest värde", "Komplett set", "Deep-tissue"],
  },
  {
    slug: "massagepistol",
    title: "Beurer MG 99 vs BDBKMG massagepistol",
    shortTitle: "Massagepistol",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/massagepistol",
    description:
      "Kompakt märkesval mot fler lägen och mer funktioner för pengarna.",
    productSlugs: ["beurer-mg-99-massagepistol", "bdbkmg-massagepistol"],
    badges: ["Känt märke", "99 lägen", "Återhämtning"],
  },
  {
    slug: "plattang",
    title: "Remington S8540 vs Remington Mini S2880",
    shortTitle: "Plattång",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/plattang",
    description:
      "Beprövad vardagsplattång mot ett ärligt begränsat reseval.",
    productSlugs: ["remington-s8540-plattang", "remington-mini-s2880-plattang"],
    badges: ["Beprövat val", "Resvänlig", "Hårstyling"],
  },
  {
    slug: "epilator",
    title: "Panasonic ES-EY30 vs Braun Silk-épil 9",
    shortTitle: "Epilator",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/epilator",
    description:
      "Prisvärt premiumval mot ett dyrare paket med fler tillbehör.",
    productSlugs: ["panasonic-es-ey30-epilator", "braun-silk-epil-9"],
    badges: ["Wet/Dry", "Premiumval", "Lenare resultat"],
  },
  {
    slug: "hartork",
    title: "Remington PROluxe vs Beurer HC 25 hårtork",
    shortTitle: "Hårtork",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/hartork",
    description:
      "Salongskraft hemma mot en lättare rese- och budgethårtork.",
    productSlugs: ["remington-proluxe-ac9140-hartork", "beurer-hc-25-hartork"],
    badges: ["2400 W", "Resvänlig", "Budgetval"],
  },
  {
    slug: "locktang",
    title: "BaByliss C325E vs TYMO CURLPRO locktång",
    shortTitle: "Locktång",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/locktang",
    description:
      "Manuellt värdeval för stora lockar mot automatisk premiumstyling.",
    productSlugs: ["babyliss-c325e-locktang", "tymo-curlpro-locktang"],
    badges: ["Mest värde", "Automatisk", "Stora lockar"],
  },
  {
    slug: "varmluftsborste",
    title: "BaByliss AS126E vs Remington AS7100 varmluftsborste",
    shortTitle: "Varmluftsborste",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/varmluftsborste",
    description:
      "Mångsidig 4-i-1 för volym mot billigare styling för kort hår.",
    productSlugs: [
      "babyliss-as126e-varmluftsborste",
      "remington-as7100-varmluftsborste",
    ],
    badges: ["4-i-1", "Budgetval", "Kort hår"],
  },
  {
    slug: "platta-eller-locka",
    title: "Platta eller locka?",
    shortTitle: "Platta eller locka?",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/platta-eller-locka",
    description:
      "Slätt, polerat och mjuka vågor mot definierade klassiska lockar.",
    productSlugs: ["remington-s8540-plattang", "babyliss-c325e-locktang"],
    badges: ["Rakt & vågor", "Definierade lockar", "Mångsidig"],
  },
  {
    slug: "varmluftsborste-eller-fon",
    title: "Varmluftsborste eller vanlig fön?",
    shortTitle: "Varmluftsborste eller fön",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/varmluftsborste-eller-fon",
    description:
      "Torka och styla i samma moment mot ren, kraftfull torkning.",
    productSlugs: [
      "babyliss-as126e-varmluftsborste",
      "remington-proluxe-ac9140-hartork",
    ],
    badges: ["Torka + styla", "Mest torkkraft", "Volym"],
  },
  {
    slug: "sommarglow-utan-sol",
    title: "Sommarglow utan sol",
    shortTitle: "Sommarglow utan sol",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/sommarglow-utan-sol",
    description:
      "Hållbar självbruna som utvecklas mot flexibel, tvättbar glow.",
    productSlugs: ["st-tropez-self-tan-express", "elf-skin-bronzing-drops"],
    badges: ["Håller i dagar", "Tvättbar glow", "Sommar"],
  },
  {
    slug: "harolja-eller-varmeskydd",
    title: "Hårolja eller värmeskydd?",
    shortTitle: "Hårolja eller värmeskydd",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/harolja-eller-varmeskydd",
    description:
      "Glans och mjukhet för torrt hår mot skydd före värmestyling.",
    productSlugs: ["moroccanoil-harolja", "loreal-elvital-varmeskydd"],
    badges: ["Skyddar vid värme", "Glans & mjukhet", "Sommarvård"],
  },
  {
    slug: "varmluftsborste-eller-plattang",
    title: "Varmluftsborste eller plattång?",
    shortTitle: "Varmluftsborste eller plattång",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/varmluftsborste-eller-plattang",
    description:
      "Volym och böj i ett steg mot slätt, polerat och mer mångsidigt.",
    productSlugs: ["babyliss-as126e-varmluftsborste", "remington-s8540-plattang"],
    badges: ["Allt-i-ett", "Slätt & polerat", "Volym"],
  },
  {
    slug: "aftersun-eller-aloe-vera",
    title: "Aftersun eller aloe vera?",
    shortTitle: "Aftersun eller aloe vera",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/aftersun-eller-aloe-vera",
    description:
      "Mjukgörande after sun-lotion för kroppen mot en lätt, svalkande aloe vera-gel.",
    productSlugs: ["nivea-sun-after-sun-lotion", "naissance-aloe-vera-gel"],
    badges: ["Svalkar", "Återfuktar", "Sommar"],
  },
  {
    slug: "harinpackning-eller-harolja",
    title: "Hårinpackning eller hårolja?",
    shortTitle: "Hårinpackning eller hårolja",
    category: "skonhet",
    categoryLabel: "Skönhet",
    href: "/skonhet/harinpackning-eller-harolja",
    description:
      "Intensiv inpackning som sköljs ur mot glansgivande leave-in-olja.",
    productSlugs: ["loreal-absolut-repair", "moroccanoil-harolja"],
    badges: ["Djup kur", "Glans & mjukhet", "Sommarvård"],
  },
  {
    slug: "kettlebell-eller-hantlar",
    title: "Kettlebell eller hantlar?",
    shortTitle: "Kettlebell eller hantlar",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/kettlebell-eller-hantlar",
    description:
      "Ett mångsidigt redskap för svingar mot ett komplett hantelset med ställning.",
    productSlugs: [
      "amazon-basics-gjutjarns-kettlebell",
      "songmics-hantelset-med-stallning",
    ],
    badges: ["Helkropp", "Set + ställning", "Hemmaträning"],
  },
  {
    slug: "foam-roller-eller-massagepistol",
    title: "Foam roller eller massagepistol?",
    shortTitle: "Foam roller eller massagepistol",
    category: "traning",
    categoryLabel: "Träning",
    href: "/traning/foam-roller-eller-massagepistol",
    description:
      "Enkel återhämtning för stora muskelgrupper mot riktad vibration på enskilda punkter.",
    productSlugs: ["bodymate-foam-roller-care", "beurer-mg-99-massagepistol"],
    badges: ["Återhämtning", "Billigast", "Riktad"],
  },
  {
    slug: "mini-projektor-eller-stjarnprojektor",
    title: "Mini-projektor eller stjärnprojektor?",
    shortTitle: "Mini- eller stjärnprojektor",
    category: "halsa",
    categoryLabel: "Hälsa",
    href: "/halsa/mini-projektor-eller-stjarnprojektor",
    description:
      "Bärbar bio för film på väggen mot en drömmig galaxhimmel på taket.",
    productSlugs: ["mini-projektor", "stjarnprojektor"],
    badges: ["Film på väggen", "Galaxhimmel", "Mys"],
  },
];

export function getComparisonsByCategory(category: ProductCategorySlug) {
  return comparisonEntries.filter((comparison) => comparison.category === category);
}

export function getRelatedComparisons(
  category: ProductCategorySlug,
  currentHref?: string,
) {
  return comparisonEntries
    .filter(
      (comparison) =>
        comparison.category === category && comparison.href !== currentHref,
    )
    .slice(0, 3);
}
