import { waveEditorialScores } from "@/lib/wave-products";

export type EditorialScore = {
  value: number;
  performance: number;
  promise: number;
  proven: number;
  total: number;
  verdict: string;
};

export const scoreWeights = {
  value: 30,
  performance: 30,
  promise: 25,
  proven: 15,
} as const;

export type ScoreTier = {
  label: "Utmärkt" | "Bra" | "Helt okej" | "Rekommenderas inte";
  tone: "excellent" | "good" | "okay" | "low";
};

export function getScoreTier(total: number): ScoreTier {
  if (total >= 90) {
    return { label: "Utmärkt", tone: "excellent" };
  }

  if (total >= 75) {
    return { label: "Bra", tone: "good" };
  }

  if (total >= 60) {
    return { label: "Helt okej", tone: "okay" };
  }

  return { label: "Rekommenderas inte", tone: "low" };
}

export const editorialScores: Record<string, EditorialScore> = {
  ...waveEditorialScores,
  "utopia-cabana-strandhandduk": {
    value: 23,
    performance: 21,
    promise: 20,
    proven: 13,
    total: 77,
    verdict: "Mjuk, sugande bomullsfrotté – tar mer plats än mikrofiber",
  },
  "fit-flip-mikrofiberhandduk": {
    value: 25,
    performance: 22,
    promise: 20,
    proven: 13,
    total: 80,
    verdict: "Snabbtorkande och kompakt – smart packval, tunnare känsla",
  },
  "cabin-max-anode-kabinvaska": {
    value: 25,
    performance: 23,
    promise: 21,
    proven: 13,
    total: 82,
    verdict: "Lätt hardcase i exakt kabinstorlek – toppval för weekend",
  },
  "taygeer-kabinryggsack": {
    value: 26,
    performance: 23,
    promise: 21,
    proven: 13,
    total: 83,
    verdict: "Rymlig 44L kabinryggsäck som gör händerna fria",
  },
  "traningsband-4-nivaer": {
    value: 26,
    performance: 22,
    promise: 21,
    proven: 11,
    total: 80,
    verdict: "Smart förstaval för hemmaträning",
  },
  "jakkofoxx-loopband": {
    value: 27,
    performance: 21,
    promise: 20,
    proven: 14,
    total: 82,
    verdict: "Mest beprövade loop-bandet för ben och rumpa",
  },
  "amazon-basics-gjutjarns-kettlebell": {
    value: 28,
    performance: 25,
    promise: 20,
    proven: 13,
    total: 86,
    verdict: "Elins val - mest kettlebell för pengarna",
  },
  "proiron-mjuk-kettlebell": {
    value: 20,
    performance: 23,
    promise: 22,
    proven: 14,
    total: 79,
    verdict: "Golvsnällt nybörjarval för hemmet",
  },
  "proiron-neoprenhantlar": {
    value: 26,
    performance: 23,
    promise: 21,
    proven: 14,
    total: 84,
    verdict: "Elins val - enklast och mest beprövat för pengarna",
  },
  "songmics-hantelset-med-stallning": {
    value: 23,
    performance: 23,
    promise: 22,
    proven: 14,
    total: 82,
    verdict: "Färdigt startset med ställning för hemmaträning",
  },
  "prosourcefit-extra-tjock-yogamatta": {
    value: 27,
    performance: 22,
    promise: 21,
    proven: 14,
    total: 84,
    verdict: "Elins val - mest komfort för pengarna",
  },
  "yogati-tpe-yogamatta": {
    value: 23,
    performance: 26,
    promise: 21,
    proven: 13,
    total: 83,
    verdict: "Greppvalet för yoga och balans",
  },
  "bodymate-foam-roller-care": {
    value: 27,
    performance: 22,
    promise: 21,
    proven: 14,
    total: 84,
    verdict: "Elins val - enkel, fast och prisvärd foam roller",
  },
  "elvire-deep-tissue-massageset": {
    value: 24,
    performance: 23,
    promise: 20,
    proven: 13,
    total: 80,
    verdict: "Komplett deep-tissue-set med tydlig caveat",
  },
  "beurer-mg-99-massagepistol": {
    value: 21,
    performance: 22,
    promise: 20,
    proven: 13,
    total: 76,
    verdict: "Tryggt, kompakt märkesval",
  },
  "bdbkmg-massagepistol": {
    value: 25,
    performance: 23,
    promise: 21,
    proven: 11,
    total: 80,
    verdict: "Mest massage för pengarna",
  },
  "remington-s8540-plattang": {
    value: 26,
    performance: 24,
    promise: 22,
    proven: 14,
    total: 86,
    verdict: "Prisvärt, beprövat vardagsval",
  },
  "remington-mini-s2880-plattang": {
    value: 22,
    performance: 16,
    promise: 20,
    proven: 11,
    total: 69,
    verdict: "Smart för resan – ärligt begränsad",
  },
  "panasonic-es-ey30-epilator": {
    value: 23,
    performance: 26,
    promise: 21,
    proven: 14,
    total: 84,
    verdict: "Prisvärt premiumval för len, smidig epilering",
  },
  "braun-silk-epil-9": {
    value: 18,
    performance: 27,
    promise: 23,
    proven: 13,
    total: 81,
    verdict: "Premiumvalet – för dig som vill ha det yppersta",
  },
  "remington-proluxe-ac9140-hartork": {
    value: 25,
    performance: 27,
    promise: 22,
    proven: 14,
    total: 88,
    verdict: "Elins val – mest hårtork för pengarna i premiumklass",
  },
  "beurer-hc-25-hartork": {
    value: 25,
    performance: 20,
    promise: 21,
    proven: 14,
    total: 80,
    verdict: "Det prisvärda rese- och budgetvalet",
  },
  "babyliss-c325e-locktang": {
    value: 25,
    performance: 22,
    promise: 20,
    proven: 14,
    total: 81,
    verdict: "Elins val - mest locktång för pengarna",
  },
  "tymo-curlpro-locktang": {
    value: 18,
    performance: 27,
    promise: 21,
    proven: 14,
    total: 80,
    verdict: "Premiumvalet - effortless för långt och tjockt hår",
  },
  "babyliss-as126e-varmluftsborste": {
    value: 24,
    performance: 22,
    promise: 20,
    proven: 12,
    total: 78,
    verdict: "Elins val - mångsidig 4-i-1 för volym och brushing",
  },
  "remington-as7100-varmluftsborste": {
    value: 24,
    performance: 17,
    promise: 19,
    proven: 12,
    total: 72,
    verdict: "Budgetvalet - billigast och bäst på kort hår",
  },
  "st-tropez-self-tan-express": {
    value: 20,
    performance: 27,
    promise: 22,
    proven: 14,
    total: 83,
    verdict: "Premiumvalet för en naturlig sommarglow",
  },
  "elf-skin-bronzing-drops": {
    value: 26,
    performance: 22,
    promise: 21,
    proven: 12,
    total: 81,
    verdict: "Prisvärt glow-val du blandar själv",
  },
  "nivea-sun-after-sun-lotion": {
    value: 28,
    performance: 24,
    promise: 22,
    proven: 14,
    total: 88,
    verdict: "Prisvärt och beprövat after sun-val",
  },
  "naissance-aloe-vera-gel": {
    value: 27,
    performance: 23,
    promise: 21,
    proven: 14,
    total: 85,
    verdict: "Prisvärd, vegansk aloe vera som svalkar efter solen",
  },
  "minimalist-hyaluronsyra-serum": {
    value: 25,
    performance: 24,
    promise: 22,
    proven: 13,
    total: 84,
    verdict: "Prisvärt fukt-serum som återfuktar på flera nivåer",
  },
  "kanzy-jojobaolja": {
    value: 26,
    performance: 23,
    promise: 22,
    proven: 14,
    total: 85,
    verdict: "Mångsidig, prisvärd jojobaolja för hud, hår & naglar",
  },
  "inkey-niacinamide-serum": {
    value: 26,
    performance: 22,
    promise: 21,
    proven: 13,
    total: 82,
    verdict: "Prisvärt niacinamide-serum som mattar fett och jämnar hudtonen",
  },
  "moroccanoil-harolja": {
    value: 19,
    performance: 28,
    promise: 23,
    proven: 15,
    total: 85,
    verdict: "Premiumvalet - ikonisk hårolja för glans och mjukhet",
  },
  "moroccanoil-torrschampo": {
    value: 19,
    performance: 25,
    promise: 22,
    proven: 14,
    total: 80,
    verdict: "Premium torrschampo som mattar fett och gulton för ljust hår",
  },
  "vxdoirk-elektrisk-fotfil": {
    value: 26,
    performance: 23,
    promise: 21,
    proven: 12,
    total: 82,
    verdict: "Prisvärt och laddbart - mjuka, sandalfina fötter hemma",
  },
  "loreal-elvital-varmeskydd": {
    value: 27,
    performance: 24,
    promise: 22,
    proven: 14,
    total: 87,
    verdict: "Prisvärt värmeskydd som skyddar håret vid styling",
  },
  "loreal-absolut-repair": {
    value: 23,
    performance: 27,
    promise: 22,
    proven: 14,
    total: 86,
    verdict: "Premium hårinpackning som räddar torrt sommarhår",
  },
  "kobo-clara-bw": {
    value: 24,
    performance: 27,
    promise: 22,
    proven: 15,
    total: 88,
    verdict: "Smart sommarro - papperslik läsro som syns i solen",
  },
  "salking-aromadiffuser": {
    value: 26,
    performance: 21,
    promise: 20,
    proven: 13,
    total: 80,
    verdict: "Prisvärd mys-diffuser med varmt sken och doft",
  },
  "solnedgangslampa": {
    value: 27,
    performance: 20,
    promise: 21,
    proven: 12,
    total: 80,
    verdict: "Prisvärt, scroll-stoppande sunset-sken för mys",
  },
  "mini-projektor": {
    value: 27,
    performance: 22,
    promise: 22,
    proven: 13,
    total: 84,
    verdict: "Prisvärd bärbar bio - film på väggen var du vill",
  },
  "stjarnprojektor": {
    value: 26,
    performance: 20,
    promise: 21,
    proven: 12,
    total: 79,
    verdict: "Scroll-stoppande galaxhimmel - drömmig mys för rummet",
  },
  "gehwol-fotpuder": {
    value: 24,
    performance: 26,
    promise: 21,
    proven: 12,
    total: 83,
    verdict: "Bra skönhetsval när du vill ha Gehwol fotpuder utan onödigt krångel.",
  },
  "braun-bikinitrimmer": {
    value: 24,
    performance: 19,
    promise: 22,
    proven: 10,
    total: 75,
    verdict: "Bra skönhetsval när du vill ha Braun Silk-épil bikinitrimmer utan onödigt krångel.",
  },
  "veet-vaxremsor": {
    value: 26,
    performance: 26,
    promise: 22,
    proven: 10,
    total: 84,
    verdict: "Bra skönhetsval när du vill ha Veet Expert vaxremsor för ben och kropp utan onödigt krångel.",
  },
  "satincare-rakgel": {
    value: 28,
    performance: 23,
    promise: 22,
    proven: 12,
    total: 85,
    verdict: "Bra skönhetsval när du vill ha Gillette Satin Care rakgel för kvinnor utan onödigt krångel.",
  },
  "merkur-safety-razor": {
    value: 24,
    performance: 25,
    promise: 22,
    proven: 14,
    total: 85,
    verdict: "Bra skönhetsval när du vill ha Merkur 34C safety razor utan onödigt krångel.",
  },
  "tweezerman-brynsax": {
    value: 24,
    performance: 28,
    promise: 22,
    proven: 14,
    total: 88,
    verdict: "Bra skönhetsval när du vill ha Tweezerman brynsax med borste utan onödigt krångel.",
  },
  "sorella-brynlaminering": {
    value: 24,
    performance: 19,
    promise: 19,
    proven: 10,
    total: 72,
    verdict: "Helt okej för rätt behov, men inte ett självklart förstaval.",
  },
  "nanobrow-brynserum": {
    value: 21,
    performance: 16,
    promise: 22,
    proven: 12,
    total: 71,
    verdict: "Helt okej för rätt behov, men inte ett självklart förstaval.",
  },
  "xlash-fransserum": {
    value: 21,
    performance: 21,
    promise: 22,
    proven: 13,
    total: 77,
    verdict: "Bra skönhetsval när du vill ha Xlash fransserum utan onödigt krångel.",
  },
  "beurer-mp48-nagellampa": {
    value: 24,
    performance: 25,
    promise: 22,
    proven: 10,
    total: 81,
    verdict: "Bra skönhetsval när du vill ha Beurer MP 48 UV/LED nagellampa utan onödigt krångel.",
  },
  "essie-gel-couture-topcoat": {
    value: 24,
    performance: 26,
    promise: 22,
    proven: 13,
    total: 85,
    verdict: "Bra skönhetsval när du vill ha essie Gel Couture topplack – gel-effekt utan lampa utan onödigt krångel.",
  },
  "glasnagelfil": {
    value: 26,
    performance: 25,
    promise: 22,
    proven: 10,
    total: 83,
    verdict: "Bra skönhetsval när du vill ha Tweezerman glasnagelfil utan onödigt krångel.",
  },
  "cnd-nagelbandsolja": {
    value: 24,
    performance: 26,
    promise: 22,
    proven: 13,
    total: 85,
    verdict: "Bra skönhetsval när du vill ha CND SolarOil nagelband- och nagelolja utan onödigt krångel.",
  },
  "opi-ridge-filler": {
    value: 24,
    performance: 25,
    promise: 21,
    proven: 13,
    total: 83,
    verdict: "Bra skönhetsval när du vill ha OPI Start-To-Finish 3-in-1 utjämnande baslack utan onödigt krångel.",
  },
  "essie-nagelhardare": {
    value: 24,
    performance: 23,
    promise: 21,
    proven: 12,
    total: 80,
    verdict: "Bra skönhetsval när du vill ha essie Hard To Resist stärkande nagellack utan onödigt krångel.",
  },
  "govee-hygrometer": {
    value: 24,
    performance: 18,
    promise: 22,
    proven: 10,
    total: 74,
    verdict: "Helt okej för rätt behov, men inte ett självklart förstaval.",
  },
  "twsoul-vattenflaska": {
    value: 26,
    performance: 19,
    promise: 22,
    proven: 8,
    total: 75,
    verdict: "Bra vardagsval, men betyget bygger fortfarande på få omdömen.",
  },
  "stanley-termos": {
    value: 21,
    performance: 27,
    promise: 21,
    proven: 15,
    total: 84,
    verdict: "Bra vardagsval när du vill ha Stanley Classic termos 1,0 L utan onödigt krångel.",
  },
  "oralb-tandborste": {
    value: 24,
    performance: 26,
    promise: 22,
    proven: 10,
    total: 82,
    verdict: "Bra vardagsval när du vill ha Oral-B iO 5S eltandborste utan onödigt krångel.",
  },
  "eufy-robotdammsugare": {
    value: 28,
    performance: 18,
    promise: 21,
    proven: 10,
    total: 77,
    verdict: "Bra vardagsval när du vill ha eufy C10 robotdammsugare utan onödigt krångel.",
  },
  "govee-led-list": {
    value: 24,
    performance: 26,
    promise: 21,
    proven: 12,
    total: 83,
    verdict: "Bra vardagsval när du vill ha Govee Neon Rope Light 2 RGBIC utan onödigt krångel.",
  },
  "gritin-laslampa": {
    value: 24,
    performance: 30,
    promise: 22,
    proven: 14,
    total: 90,
    verdict: "Utmärkt vardagsval med starka köparsignaler och tydlig nytta.",
  },
  "soundcore-hogtalare": {
    value: 24,
    performance: 26,
    promise: 22,
    proven: 13,
    total: 85,
    verdict: "Bra vardagsval när du vill ha soundcore Motion 300 bluetooth-högtalare utan onödigt krångel.",
  },
  "loop-oronproppar": {
    value: 24,
    performance: 18,
    promise: 22,
    proven: 15,
    total: 79,
    verdict: "Bra vardagsval när du vill ha Loop Quiet 2 öronproppar för sömn utan onödigt krångel.",
  },
  "manta-sovmask": {
    value: 21,
    performance: 23,
    promise: 21,
    proven: 14,
    total: 79,
    verdict: "Bra vardagsval när du vill ha Manta Sleep Mask – 100% mörkläggande sovmask utan onödigt krångel.",
  },
  "philips-wake-up-light": {
    value: 24,
    performance: 23,
    promise: 21,
    proven: 13,
    total: 81,
    verdict: "Bra vardagsval när du vill ha Philips Wake-up Light HF3651/01 utan onödigt krångel.",
  },
  "magicteam-white-noise": {
    value: 28,
    performance: 23,
    promise: 22,
    proven: 14,
    total: 87,
    verdict: "Bra vardagsval när du vill ha Magicteam white noise-maskin utan onödigt krångel.",
  },
  "withings-personvag": {
    value: 21,
    performance: 23,
    promise: 22,
    proven: 10,
    total: 76,
    verdict: "Bra vardagsval när du vill ha Withings Body Smart digital personvåg utan onödigt krångel.",
  },
  "mattibi-spikmatta": {
    value: 26,
    performance: 25,
    promise: 21,
    proven: 10,
    total: 82,
    verdict: "Bra vardagsval när du vill ha Mattibi spikmatta / akupressurmatta med kudde utan onödigt krångel.",
  },
  "beurer-varmedyna": {
    value: 24,
    performance: 18,
    promise: 21,
    proven: 13,
    total: 76,
    verdict: "Bra vardagsval när du vill ha Beurer HK Comfort värmedyna utan onödigt krångel.",
  },
  "beurer-fotmassage": {
    value: 21,
    performance: 14,
    promise: 16,
    proven: 12,
    total: 63,
    verdict: "Helt okej, men svagare köparsignal gör att Elin skulle jämföra alternativen först.",
  },
  "renpho-massagekudde": {
    value: 24,
    performance: 19,
    promise: 21,
    proven: 14,
    total: 78,
    verdict: "Bra vardagsval när du vill ha RENPHO shiatsu massagekudde med värme utan onödigt krångel.",
  },
  "beurer-luftkylare": {
    value: 21,
    performance: 10,
    promise: 17,
    proven: 10,
    total: 58,
    verdict: "Hoppa över om du vill kyla ett helt rum; välj hellre en riktig fläkt i katalogen.",
  },
  "xiaomi-bordsflakt": {
    value: 24,
    performance: 28,
    promise: 20,
    proven: 7,
    total: 79,
    verdict: "Bra vardagsval, men betyget bygger fortfarande på få omdömen.",
  },
  "jisulife-handflakt": {
    value: 24,
    performance: 21,
    promise: 22,
    proven: 10,
    total: 77,
    verdict: "Bra vardagsval när du vill ha JISULIFE Pro1 handfläkt utan onödigt krångel.",
  },
  "ella-tyngdtacke": {
    value: 26,
    performance: 25,
    promise: 19,
    proven: 13,
    total: 83,
    verdict: "Bra vardagsval när du vill ha Ella tyngdtäcke 9 kg utan onödigt krångel.",
  },
  "levoit-luftfuktare": {
    value: 24,
    performance: 23,
    promise: 21,
    proven: 15,
    total: 83,
    verdict: "Bra vardagsval när du vill ha Levoit Smart 6L luftfuktare utan onödigt krångel.",
  },
  "pro-breeze-luftavfuktare": {
    value: 26,
    performance: 21,
    promise: 21,
    proven: 10,
    total: 78,
    verdict: "Bra vardagsval när du vill ha Pro Breeze luftavfuktare 20 l/dygn utan onödigt krångel.",
  },
  "fitgriff-lifting-straps": {
    value: 26,
    performance: 18,
    promise: 21,
    proven: 10,
    total: 75,
    verdict: "Bra träningsval när du vill ha Fitgriff lifting straps / dragremmar utan onödigt krångel.",
  },
  "fuel24-vattenflaska": {
    value: 26,
    performance: 25,
    promise: 22,
    proven: 13,
    total: 86,
    verdict: "Bra träningsval när du vill ha Fuel24 vattenflaska / gym jug utan onödigt krångel.",
  },
  "salomon-loparvast": {
    value: 21,
    performance: 28,
    promise: 22,
    proven: 8,
    total: 79,
    verdict: "Bra träningsval, men betyget bygger fortfarande på få omdömen.",
  },
  "rehband-knaskydd": {
    value: 21,
    performance: 23,
    promise: 22,
    proven: 8,
    total: 74,
    verdict: "Helt okej, men underlaget är tunt så köp bara om behovet matchar exakt.",
  },
  "gvolatee-agility-stege": {
    value: 28,
    performance: 25,
    promise: 22,
    proven: 13,
    total: 88,
    verdict: "Bra träningsval när du vill ha Gvolatee agility-stege med koner utan onödigt krångel.",
  },
  "dh-fitlife-studsmatta": {
    value: 26,
    performance: 25,
    promise: 22,
    proven: 10,
    total: 83,
    verdict: "Bra träningsval när du vill ha DH FitLife fitnesstudsmatta med handtag utan onödigt krångel.",
  },
  "gorilla-core-slider": {
    value: 25,
    performance: 23,
    promise: 18,
    proven: 5,
    total: 71,
    verdict: "Helt okej, men underlaget är tunt så köp bara om behovet matchar exakt.",
  },
  "reebok-stepbrada": {
    value: 23,
    performance: 30,
    promise: 22,
    proven: 13,
    total: 88,
    verdict: "Bra träningsval när du vill ha Reebok Step justerbar stepbräda utan onödigt krångel.",
  },
  "g5-pilatesring": {
    value: 24,
    performance: 25,
    promise: 22,
    proven: 10,
    total: 81,
    verdict: "Bra träningsval när du vill ha G5 HT Sport pilatesring utan onödigt krångel.",
  },
  "bodymate-yogabalte": {
    value: 26,
    performance: 28,
    promise: 22,
    proven: 10,
    total: 86,
    verdict: "Bra träningsval när du vill ha BODYMATE yogabälte / yoga strap utan onödigt krångel.",
  },
  "bodymate-yogablock": {
    value: 26,
    performance: 30,
    promise: 22,
    proven: 12,
    total: 90,
    verdict: "Utmärkt träningsval med starka köparsignaler och tydlig nytta.",
  },
  "cpsports-lyftarbalte": {
    value: 24,
    performance: 23,
    promise: 20,
    proven: 7,
    total: 74,
    verdict: "Helt okej, men underlaget är tunt så köp bara om behovet matchar exakt.",
  },
  "asipro-handledslindor": {
    value: 26,
    performance: 25,
    promise: 21,
    proven: 13,
    total: 85,
    verdict: "Bra träningsval när du vill ha ASIPRO handledslindor / wrist wraps utan onödigt krångel.",
  },
  "ihuan-traningshandskar": {
    value: 26,
    performance: 26,
    promise: 21,
    proven: 15,
    total: 88,
    verdict: "Bra träningsval när du vill ha ihuan träningshandskar med handledsstöd utan onödigt krångel.",
  },
  "elvire-miniband": {
    value: 26,
    performance: 29,
    promise: 21,
    proven: 14,
    total: 90,
    verdict: "Utmärkt träningsval med starka köparsignaler och tydlig nytta.",
  },
  "gorilla-gymnastikringar": {
    value: 26,
    performance: 21,
    promise: 20,
    proven: 8,
    total: 75,
    verdict: "Bra träningsval, men betyget bygger fortfarande på få omdömen.",
  },
  "gorilla-push-up-handtag": {
    value: 26,
    performance: 19,
    promise: 22,
    proven: 10,
    total: 77,
    verdict: "Bra träningsval när du vill ha Gorilla Sports push up-handtag utan onödigt krångel.",
  },
  "iron-gym-pull-up-bar": {
    value: 21,
    performance: 14,
    promise: 17,
    proven: 3,
    total: 55,
    verdict: "Vänta eller välj en mer beprövad pull-up-lösning; ett enda omdöme räcker inte.",
  },
  "amonax-maghjul": {
    value: 26,
    performance: 23,
    promise: 22,
    proven: 13,
    total: 84,
    verdict: "Bra träningsval när du vill ha Amonax maghjul / ab wheel med knämatta utan onödigt krångel.",
  },
  "gorilla-balansplatta": {
    value: 23,
    performance: 17,
    promise: 18,
    proven: 5,
    total: 63,
    verdict: "Helt okej, men underlaget är tunt så köp bara om behovet matchar exakt.",
  },
  "gorilla-gymboll": {
    value: 25,
    performance: 23,
    promise: 18,
    proven: 5,
    total: 71,
    verdict: "Helt okej, men underlaget är tunt så köp bara om behovet matchar exakt.",
  },
  "bowflex-selecttech-552i": {
    value: 20,
    performance: 27,
    promise: 18,
    proven: 5,
    total: 70,
    verdict: "Helt okej, men underlaget är tunt så köp bara om behovet matchar exakt.",
  },
  "real-techniques-svamp": {
    value: 26,
    performance: 18,
    promise: 21,
    proven: 10,
    total: 75,
    verdict: "Bra skönhetsval när du vill ha Real Techniques Miracle Complexion Sponge utan onödigt krångel.",
  },
  "real-techniques-borstar": {
    value: 24,
    performance: 29,
    promise: 22,
    proven: 15,
    total: 90,
    verdict: "Utmärkt skönhetsval med starka köparsignaler och tydlig nytta.",
  },
  "press-on-naglar": {
    value: 24,
    performance: 26,
    promise: 20,
    proven: 8,
    total: 78,
    verdict: "Bra skönhetsval, men betyget bygger fortfarande på få omdömen.",
  },
  "beurer-nagelvard-set": {
    value: 24,
    performance: 26,
    promise: 22,
    proven: 14,
    total: 86,
    verdict: "Bra skönhetsval när du vill ha Beurer MP 62 manikyr- och pedikyrset utan onödigt krångel.",
  },
  "flexitol-halkram": {
    value: 26,
    performance: 26,
    promise: 21,
    proven: 12,
    total: 85,
    verdict: "Bra skönhetsval när du vill ha Flexitol Heel Balm 25% Urea utan onödigt krångel.",
  },
  "plantifique-foot-peel": {
    value: 26,
    performance: 23,
    promise: 21,
    proven: 15,
    total: 85,
    verdict: "Bra skönhetsval när du vill ha Plantifique Peach Foot Exfoliation Mask utan onödigt krångel.",
  },
  "philips-ansiktstrimmer": {
    value: 24,
    performance: 21,
    promise: 22,
    proven: 12,
    total: 79,
    verdict: "Bra skönhetsval när du vill ha Philips Facial Hair Remover 5000 Series utan onödigt krångel.",
  },
  "braun-ipl-pro5": {
    value: 24,
    performance: 21,
    promise: 22,
    proven: 13,
    total: 80,
    verdict: "Bra skönhetsval när du vill ha Braun Silk-expert Pro 5 IPL utan onödigt krångel.",
  },
  "philips-rakapparat-dam": {
    value: 24,
    performance: 23,
    promise: 22,
    proven: 10,
    total: 79,
    verdict: "Bra skönhetsval när du vill ha Philips Lady Shaver Series 8000 utan onödigt krångel.",
  },
  "tree-hut-kroppsskrubb": {
    value: 26,
    performance: 28,
    promise: 21,
    proven: 14,
    total: 89,
    verdict: "Bra skönhetsval när du vill ha Tree Hut Vanilla Shea Sugar Scrub utan onödigt krångel.",
  },
  "bondi-sands-vante": {
    value: 24,
    performance: 29,
    promise: 22,
    proven: 15,
    total: 90,
    verdict: "Utmärkt skönhetsval med starka köparsignaler och tydlig nytta.",
  },
  "tanologist-tan-drops": {
    value: 26,
    performance: 21,
    promise: 22,
    proven: 13,
    total: 82,
    verdict: "Bra skönhetsval när du vill ha Tanologist Self Tan Drops Dark – tanning drops utan onödigt krångel.",
  },
  "bondi-sands-mousse": {
    value: 24,
    performance: 21,
    promise: 21,
    proven: 12,
    total: 78,
    verdict: "Bra skönhetsval när du vill ha Bondi Sands Self Tanning Foam Ultra Dark – brun utan sol utan onödigt krångel.",
  },
  "candure-frisorsax": {
    value: 28,
    performance: 27,
    promise: 21,
    proven: 14,
    total: 90,
    verdict: "Utmärkt skönhetsval med starka köparsignaler och tydlig nytta.",
  },
  "maria-nila-texturspray": {
    value: 21,
    performance: 21,
    promise: 20,
    proven: 8,
    total: 70,
    verdict: "Helt okej, men underlaget är tunt så köp bara om behovet matchar exakt.",
  },
  "got2b-glued-harspray": {
    value: 26,
    performance: 27,
    promise: 21,
    proven: 14,
    total: 88,
    verdict: "Bra skönhetsval när du vill ha Got2b Glued hårspray utan onödigt krångel.",
  },
  "wella-eimi-mousse": {
    value: 26,
    performance: 25,
    promise: 21,
    proven: 13,
    total: 85,
    verdict: "Bra skönhetsval när du vill ha Wella EIMI Extra Volume Mousse utan onödigt krångel.",
  },
  "osis-volympuder": {
    value: 24,
    performance: 23,
    promise: 21,
    proven: 13,
    total: 81,
    verdict: "Bra skönhetsval när du vill ha Schwarzkopf OSiS+ Dust It – volympuder utan onödigt krångel.",
  },
  "denman-d3-borste": {
    value: 24,
    performance: 27,
    promise: 21,
    proven: 15,
    total: 87,
    verdict: "Bra skönhetsval när du vill ha Denman D3 Original Styler – 7 rader utan onödigt krångel.",
  },
  "wet-brush-original": {
    value: 24,
    performance: 30,
    promise: 21,
    proven: 15,
    total: 90,
    verdict: "Utmärkt skönhetsval med starka köparsignaler och tydlig nytta.",
  },
  "kitsch-claw-clips": {
    value: 24,
    performance: 25,
    promise: 21,
    proven: 12,
    total: 82,
    verdict: "Bra skönhetsval när du vill ha Kitsch Jumbo Claw Clips utan onödigt krångel.",
  },
  "kitsch-heatless-curls": {
    value: 24,
    performance: 19,
    promise: 21,
    proven: 15,
    total: 79,
    verdict: "Bra skönhetsval när du vill ha Kitsch Heatless Satin Curling Set utan onödigt krångel.",
  },
  "cantu-satin-bonnet": {
    value: 23,
    performance: 12,
    promise: 15,
    proven: 8,
    total: 58,
    verdict: "Välj hellre ett mer beprövat satin-alternativ innan den här.",
  },
  "microfiberhandduk-har": {
    value: 26,
    performance: 26,
    promise: 21,
    proven: 14,
    total: 87,
    verdict: "Bra skönhetsval när du vill ha Kitsch Microfiber Hair Towel Wrap utan onödigt krångel.",
  },
  "värmeskyddsspray-got2b": {
    value: 28,
    performance: 19,
    promise: 22,
    proven: 13,
    total: 82,
    verdict: "Bra skönhetsval när du vill ha Got2b Guardian Angel värmeskyddsspray utan onödigt krångel.",
  },
  "maui-curl-smoothie": {
    value: 26,
    performance: 27,
    promise: 21,
    proven: 14,
    total: 88,
    verdict: "Bra skönhetsval när du vill ha Maui Moisture Curl Quench+ Coconut Oil Curl Smoothie utan onödigt krångel.",
  },
  "cantu-leave-in-conditioner": {
    value: 26,
    performance: 23,
    promise: 21,
    proven: 15,
    total: 85,
    verdict: "Bra skönhetsval när du vill ha Cantu Shea Butter Leave-In Conditioning Repair Cream utan onödigt krångel.",
  },
  "inkey-scalp-scrub": {
    value: 26,
    performance: 19,
    promise: 22,
    proven: 13,
    total: 80,
    verdict: "Bra skönhetsval när du vill ha The INKEY List Glycolic Acid Exfoliating Scalp Scrub utan onödigt krångel.",
  },
  "mielle-rosemary-oil": {
    value: 24,
    performance: 23,
    promise: 22,
    proven: 13,
    total: 82,
    verdict: "Bra skönhetsval när du vill ha Mielle Rosemary Mint Scalp & Hair Strengthening Oil utan onödigt krångel.",
  },
  "olaplex-no3-treatment": {
    value: 21,
    performance: 25,
    promise: 21,
    proven: 12,
    total: 79,
    verdict: "Bra skönhetsval när du vill ha Olaplex No.3 Hair Perfector – inpackning för skadat hår utan onödigt krångel.",
  },
  "olaplex-no5-conditioner": {
    value: 21,
    performance: 26,
    promise: 21,
    proven: 14,
    total: 82,
    verdict: "Bra skönhetsval när du vill ha Olaplex No.5 Bond Maintenance Conditioner utan onödigt krångel.",
  },
  "olaplex-no4-shampoo": {
    value: 21,
    performance: 26,
    promise: 21,
    proven: 14,
    total: 82,
    verdict: "Bra skönhetsval när du vill ha Olaplex No.4 Bond Maintenance Shampoo utan onödigt krångel.",
  },
  "neutrogena-hand-cream": {
    value: 26,
    performance: 26,
    promise: 20,
    proven: 14,
    total: 86,
    verdict: "Bra skönhetsval när du vill ha Neutrogena Norwegian Formula – handkräm utan onödigt krångel.",
  },
  "biotherm-lait-corporel": {
    value: 24,
    performance: 28,
    promise: 20,
    proven: 13,
    total: 85,
    verdict: "Bra skönhetsval när du vill ha Biotherm Lait Corporel – återfuktande kroppslotion utan onödigt krångel.",
  },
  "olay-regenerist-night-cream": {
    value: 24,
    performance: 27,
    promise: 22,
    proven: 14,
    total: 87,
    verdict: "Bra skönhetsval när du vill ha Olay Regenerist Night Recovery – nattkräm utan onödigt krångel.",
  },
  "dior-lip-glow-oil": {
    value: 20,
    performance: 25,
    promise: 19,
    proven: 8,
    total: 72,
    verdict: "Helt okej, men underlaget är tunt så köp bara om behovet matchar exakt.",
  },
  "cosrx-acne-pimple-patch": {
    value: 24,
    performance: 26,
    promise: 21,
    proven: 15,
    total: 86,
    verdict: "Bra skönhetsval när du vill ha COSRX Acne Pimple Master Patch utan onödigt krångel.",
  },
  "nature-spell-face-oil": {
    value: 24,
    performance: 28,
    promise: 19,
    proven: 7,
    total: 78,
    verdict: "Bra skönhetsval, men betyget bygger fortfarande på få omdömen.",
  },
  "mario-badescu-facial-spray": {
    value: 24,
    performance: 26,
    promise: 20,
    proven: 10,
    total: 80,
    verdict: "Bra skönhetsval när du vill ha Mario Badescu Facial Spray – Aloe, Herbs & Rosewater utan onödigt krångel.",
  },
  "inkey-peptide-moisturizer": {
    value: 26,
    performance: 19,
    promise: 22,
    proven: 10,
    total: 77,
    verdict: "Bra skönhetsval när du vill ha The INKEY List Peptide Moisturiser utan onödigt krångel.",
  },
  "anua-azelaic-acid-serum": {
    value: 24,
    performance: 25,
    promise: 21,
    proven: 13,
    total: 83,
    verdict: "Bra skönhetsval när du vill ha Anua Azelaic Acid 10 + Hyaluron Soothing Serum utan onödigt krångel.",
  },
  "beauty-of-joseon-propolis-serum": {
    value: 24,
    performance: 23,
    promise: 21,
    proven: 13,
    total: 81,
    verdict: "Bra skönhetsval när du vill ha Beauty of Joseon Glow Serum – Propolis + Niacinamide utan onödigt krångel.",
  },
  "cosrx-centella-ampoule": {
    value: 24,
    performance: 25,
    promise: 22,
    proven: 10,
    total: 81,
    verdict: "Bra skönhetsval när du vill ha COSRX Centella Aqua Soothing Ampoule utan onödigt krångel.",
  },
  "beauty-of-joseon-centella-mask": {
    value: 24,
    performance: 19,
    promise: 19,
    proven: 7,
    total: 69,
    verdict: "Helt okej, men underlaget är tunt så köp bara om behovet matchar exakt.",
  },
  "some-by-mi-matcha-clay-mask": {
    value: 26,
    performance: 25,
    promise: 21,
    proven: 10,
    total: 82,
    verdict: "Bra skönhetsval när du vill ha Some By Mi Super Matcha Pore Clean Clay Mask utan onödigt krångel.",
  },
  "divain-caffeine-eye-serum": {
    value: 24,
    performance: 21,
    promise: 20,
    proven: 7,
    total: 72,
    verdict: "Helt okej, men underlaget är tunt så köp bara om behovet matchar exakt.",
  },
  "cetaphil-moisturizing-cream": {
    value: 28,
    performance: 28,
    promise: 22,
    proven: 13,
    total: 91,
    verdict: "Utmärkt skönhetsval med starka köparsignaler och tydlig nytta.",
  },
  "cosrx-aha-bha-toner": {
    value: 26,
    performance: 25,
    promise: 22,
    proven: 14,
    total: 87,
    verdict: "Bra skönhetsval när du vill ha COSRX AHA/BHA Clarifying Treatment Toner utan onödigt krångel.",
  },
  "bioderma-sensibio-h2o": {
    value: 24,
    performance: 30,
    promise: 21,
    proven: 15,
    total: 90,
    verdict: "Utmärkt skönhetsval med starka köparsignaler och tydlig nytta.",
  },
  "some-by-mi-cleansing-oil": {
    value: 26,
    performance: 21,
    promise: 19,
    proven: 8,
    total: 74,
    verdict: "Helt okej, men underlaget är tunt så köp bara om behovet matchar exakt.",
  },
  "cetaphil-gentle-cleanser": {
    value: 26,
    performance: 28,
    promise: 22,
    proven: 12,
    total: 88,
    verdict: "Bra skönhetsval när du vill ha Cetaphil Gentle Skin Cleanser – mild ansiktsrengöring utan onödigt krångel.",
  },
  "paulas-choice-2-bha": {
    value: 24,
    performance: 21,
    promise: 21,
    proven: 15,
    total: 81,
    verdict: "Bra skönhetsval när du vill ha Paula's Choice Skin Perfecting 2% BHA Liquid Exfoliant utan onödigt krångel.",
  },
  "purest-aha-bha-peeling": {
    value: 26,
    performance: 23,
    promise: 21,
    proven: 12,
    total: 82,
    verdict: "Bra skönhetsval när du vill ha The Purest Solutions AHA 10% + BHA 2% Exfoliating Peeling utan onödigt krångel.",
  },
  "celdyque-bakuchiol-serum": {
    value: 26,
    performance: 26,
    promise: 21,
    proven: 12,
    total: 85,
    verdict: "Bra skönhetsval när du vill ha CELDYQUE Bakuchiol Concentrate Serum – retinol-alternativ utan onödigt krångel.",
  },
  "eric-flag-viktvast": {
    value: 24,
    performance: 28,
    promise: 22,
    proven: 13,
    total: 87,
    verdict: "Bra träningsval när du vill ha Eric Flag viktväst med justerbar vikt utan onödigt krångel.",
  },
  "portentum-hopprep": {
    value: 26,
    performance: 23,
    promise: 22,
    proven: 12,
    total: 83,
    verdict: "Bra träningsval när du vill ha PORTENTUM hopprep med kullager utan onödigt krångel.",
  },
  "levoit-core-200s-luftrenare": {
    value: 26,
    performance: 27,
    promise: 21,
    proven: 15,
    total: 89,
    verdict: "Bra vardagsval när du vill ha Levoit Core 200S luftrenare med HEPA-filter utan onödigt krångel.",
  },
  "tangle-teezer-original": {
    value: 24,
    performance: 30,
    promise: 21,
    proven: 15,
    total: 90,
    verdict: "Utmärkt skönhetsval med starka köparsignaler och tydlig nytta.",
  },
  "silkesorngott-mullbarssilke": {
    value: 26,
    performance: 25,
    promise: 21,
    proven: 14,
    total: 86,
    verdict: "Bra skönhetsval när du vill ha Örngott i 100% mullbärssilke utan onödigt krångel.",
  },
  "gua-sha-rosenkvarts": {
    value: 26,
    performance: 19,
    promise: 19,
    proven: 7,
    total: 71,
    verdict: "Helt okej, men underlaget är tunt så köp bara om behovet matchar exakt.",
  },
  "laneige-lip-sleeping-mask": {
    value: 24,
    performance: 26,
    promise: 22,
    proven: 10,
    total: 82,
    verdict: "Bra skönhetsval när du vill ha LANEIGE Lip Sleeping Mask – läppmask utan onödigt krångel.",
  },
  "la-roche-posay-cicaplast-b5": {
    value: 24,
    performance: 29,
    promise: 22,
    proven: 14,
    total: 89,
    verdict: "Bra skönhetsval när du vill ha La Roche-Posay Cicaplast Baume B5+ utan onödigt krångel.",
  },
  "cerave-hydrating-cleanser": {
    value: 26,
    performance: 26,
    promise: 22,
    proven: 15,
    total: 89,
    verdict: "Bra skönhetsval när du vill ha CeraVe Hydrating Cleanser – ansiktsrengöring utan onödigt krångel.",
  },
  "la-roche-posay-vitamin-c10-serum": {
    value: 24,
    performance: 23,
    promise: 21,
    proven: 10,
    total: 78,
    verdict: "Bra skönhetsval när du vill ha La Roche-Posay Pure Vitamin C10 Serum utan onödigt krångel.",
  },
  "dreo-cruiser-pro-tornflakt": {
    value: 24,
    performance: 27,
    promise: 22,
    proven: 15,
    total: 88,
    verdict: "Bra vardagsval när du vill ha Dreo Cruiser Pro T1 tornfläkt utan onödigt krångel.",
  },
  "honeywell-turboforce-ht900e": {
    value: 28,
    performance: 23,
    promise: 21,
    proven: 15,
    total: 87,
    verdict: "Bra vardagsval när du vill ha Honeywell TurboForce HT900E bordsfläkt utan onödigt krångel.",
  },
  "midea-fz10-tornflakt": {
    value: 28,
    performance: 23,
    promise: 21,
    proven: 13,
    total: 85,
    verdict: "Bra vardagsval när du vill ha Midea FZ10-17JR tornfläkt utan onödigt krångel.",
  },
  "cosrx-snail-mucin-essence": {
    value: 26,
    performance: 25,
    promise: 21,
    proven: 14,
    total: 86,
    verdict: "Bra skönhetsval när du vill ha COSRX Snail Mucin 74% + Niacinamide Dual Essence utan onödigt krångel.",
  },
};

export function getEditorialScore(productSlug: string) {
  return editorialScores[productSlug];
}

/**
 * Builds a schema.org Review node from Elins poäng for a product slug.
 * Returns undefined when no editorial score exists (JSON.stringify drops it,
 * so it is safe to spread directly into a Product schema's `review` field).
 *
 * Compliance: a single editorial review authored by "Elins val" — never an
 * AggregateRating with a fabricated review count.
 */
export function buildElinReviewNode(productSlug: string) {
  const score = editorialScores[productSlug];

  if (!score) {
    return undefined;
  }

  const tier = getScoreTier(score.total);

  return {
    "@type": "Review",
    reviewRating: {
      "@type": "Rating",
      ratingValue: score.total,
      bestRating: 100,
      worstRating: 0,
    },
    author: {
      "@type": "Organization",
      name: "Elins val",
    },
    name: `Elins poäng: ${score.total}/100 – ${tier.label}`,
    reviewBody: score.verdict,
  };
}
